	INCLUDE 'VICMAIN_FOR'
	SUBROUTINE MAIN44
C 	   PROGRAM THSTGEN TO TEST HSTGNB
	INTEGER HIST(256),SLO,SSO
	BYTE BUF(100000)
        DATA HIST/256*0/

        CALL XVEACTION('SA',' ')
        CALL XVUNIT(IUNIT,'INP',1,STAT,' ')
        CALL XVOPEN(IUNIT,STAT,' ')
        CALL XVSIZE(SLO,SSO,NLO,NSO,NLI,NSI)
	DO LINE=SLO,SLO+NLO-1
           CALL XVREAD(IUNIT,BUF,STAT,'LINE',LINE,'SAMP',SSO,
     &                 'NSAMPS',NSO,' ')
  	   CALL HSTGNB(NSO,BUF,HIST)
	ENDDO
	CALL PRNT(4,256,HIST,' HIST=.')

        CALL ZIA(HIST,256)
	DO LINE=SLO,SLO+NLO-1
           CALL XVREAD(IUNIT,BUF,STAT,'LINE',LINE,'SAMP',SSO,
     &                 'NSAMPS',NSO,' ')
  	   CALL TZHSTGNB(NSO,BUF,HIST)
	ENDDO
	CALL PRNT(4,256,HIST,' HIST=.')

        CALL XVCLOSE(IUNIT,STAT,' ')
	RETURN
	END
