C  THIS IS A TEST PROGRAM FOR THE FORTRAN CALLABLE PORTION OF THE
C  GTPRCS SUBROUTINE

        SUBROUTINE TGTPRCS()

	CHARACTER*8 B
        CHARACTER*30 MSG

	CALL GTPRCS(B)
	WRITE(MSG,100) B
 100    FORMAT(A8)
        CALL XVMESSAGE(MSG,' ')
        CALL XVMESSAGE(' ',' ')
	RETURN
	END
