      INCLUDE 'VICMAIN_FOR'
C  IBIS ROUTINE POLYGEN
C  PURPOSE:  GENERATE IBIS POLYGON FILE FROM DATA COMMANDS
C  USER PARAMETERS:
C  DATA,X1,Y1,...,XN,YN  THE POINTS XI,YI ARE INSERTED IN ORDER INTO THE
C                OUTPUT FILE.
C  MDATA,X1,Y1,A1,B1,K1,...,XM,YM,AM,BM,KM   FOR EACH FIVE-TUPLE KI POIN
C                GENERATED IN A UNIFORM STRAIGHT LINE BETWEEN XI,YI AND
C                AND INSERTED IN ORDER INTO THE OUTPUT FILE.
C
C	Revision 2:  March 1986		Frank Evans
C		Put in calls to graphics routines to fix xvopen bug
C
C
      SUBROUTINE MAIN44
      IMPLICIT INTEGER(A-Z)
      REAL	DATAARRAY(500), MDATAARRAY(500)
      REAL	DL,DS,SL,SS 
C
C---- READ PARAMETERS. OPEN FILE.
C
      CALL XVPARM ('DATA', DATAARRAY, NDATA, DATADEF,0)
      CALL XVPARM ('MDATA', MDATAARRAY, NMDATA, MDATADEF,0)
      IF (DATADEF .EQ. 1 .AND. MDATADEF .EQ. 1) GO TO 999
C
C
C--	OPEN IBIS GRAPHICS-1 FILE
      CALL WRGR (1, 1, 2)
C
C
      IF (DATADEF .EQ. 1) GO TO 5
C
C---- PROCESS "DATA".
C
      DO I = 1, NDATA, 2
	 CALL PUTGR (1, DATAARRAY(I), DATAARRAY(I+1) )
      ENDDO
C
C---- PROCESS "MDATA".
C
    5 IF (MDATADEF .EQ. 1) GO TO 6
      DO I = 1, NMDATA, 5
         NP1 = MDATAARRAY(I+4)
         DL = (MDATAARRAY(I+2)-MDATAARRAY(I))/(NP1-1)
         DS = (MDATAARRAY(I+3)-MDATAARRAY(I+1))/(NP1-1)
         SL = MDATAARRAY(I)
         SS = MDATAARRAY(I+1)
         DO J = 1, NP1
            CALL PUTGR (1, SL+(J-1)*DL, SS+(J-1)*DS)
         ENDDO
         CALL PUTGR (1, 0.0, 0.0)
      ENDDO
C
    6 CALL CLGR (1)
C
      RETURN
  999 CALL ABEND
      RETURN
      END
