/*

MP_INIT.H

	Defines mpMAP_PROJ_TYPES, mpMAP_PROJ_BITS, mpKEYWORD_TO_CODE.

*/

	/* An array of all the valid, currently supported map	*/
	/* projections. Synonyms are listed directly beneath 	*/
	/* the PDS standard name for the map projection type.   */

char mpMAP_PROJ_TYPES[mpNUMBER_OF_PROJECTIONS][mpMAX_KEYWD_LENGTH] = {

	mpALBERS, 			/* Alber's Equal-Area Conic 	*/
	mpALBERS_ONE_PARALLEL, 
	mpALBERS_TWO_PARALLELS,		

	mpCYLINDRICAL_EQUAL_AREA,	/* Cylindrical Equal-Area	*/
	mpNORMAL_CYLINDRICAL, 

	mpEQUIDISTANT, 			/* Equidistant Cylindrical	*/
	mpCYLINDRICAL, 
	mpRECTANGULAR,
	mpSIMPLE_CYLINDRICAL, 
	mpOBLIQUE_SIMPLE_CYLINDRICAL,

	mpLAMBERT_AZIMUTHAL,		/* Lambert Azimuthal Equal-Area */

	mpLAMBERT, 			/* Lambert Conformal Conic	*/
	mpLAMBERT_CONFORMAL,
	mpLAMBERT_ONE_PARALLEL,
	mpLAMBERT_TWO_PARALLELS,

	mpMERCATOR, 			/* Mercator			*/
	mpTRANSVERSE_MERCATOR,

	mpMOLLWEIDE,			/* Molleweide (Homalographic)	*/
	mpHOMALOGRAPHIC,		

	mpORTHOGRAPHIC,			/* Orthographic			*/
	mpOBLIQUE_ORTHOGRAPHIC, 
	mpPOLAR_ORTHOGRAPHIC,

	mpSINUSOIDAL, 			/* Sinusoidal			*/
	mpOBLIQUE_SINUSOIDAL,

	mpSTEREOGRAPHIC, 		/* Stereographic		*/
	mpOBLIQUE_STEREOGRAPHIC, 
	mpPOLAR_STEREOGRAPHIC,

	mpPOINT_PERSPECTIVE		/* Perspective                  */
};

	/* these flags define which items in the MAP_PROJ group are 
	 * valid for the various map projections types: */

int mpMAP_PROJ_BITS[mpNUMBER_OF_PROJECTIONS] = {

	0x03773,		/* ALBERS			*/
	0x01773,		/* ALBERS, ONE PARALLEL		*/
	0x03773,		/* ALBERS, TWO PARALLELS	*/

	0x01773,		/* CYLINDRICAL EQUAL-AREA	*/

	0x01773,		/* EQUIDISTANT	 		*/
	0x01773,		/* CYLINDRICAL	 		*/
	0x01773,		/* RECTANGULAR	 		*/
	0x01773,		/* NORMAL CYLINDRICAL 		*/
	0x01773,		/* SIMPLE CYLINDRICAL 		*/
	0x01773,		/* OBLIQUE SIMPLE CYLINDRICAL 	*/

	0x01773,		/* LAMBERT AZIMUTHAL		*/

	0x03773,		/* LAMBERT  			*/
	0x03773,		/* LAMBERT CONFORMAL 		*/
	0x01773,		/* LAMBERT, ONE PARALLEL	*/
	0x03773,		/* LAMBERT, TWO PARALLELS 	*/

	0x00773,		/* MERCATOR 			*/
	0x00773,		/* TRANSVERSE MERCATOR 		*/

	0x00773,		/* MOLLWEIDE 			*/
	0x00773,		/* HOMALOGRAPHIC 		*/

	0x00773,		/* ORTHOGRAPHIC 		*/
	0x00773,		/* POLAR ORTHOGRAPHIC 		*/
	0x00773,		/* OBLIQUE ORTHOGRAPHIC 	*/

	0x00773,		/* SINUSOIDAL 			*/
	0x00773,		/* OBLIQUE SINUSOIDAL 		*/

	0x00773,		/* STEREOGRAPHIC 		*/
	0x00773,		/* POLAR STEREOGRAPHIC 		*/
	0x00773,		/* OBLIQUE STEREOGRAPHIC 	*/

	0			/* POINT PERSPECTIVE 		*/
};

	/* Initialization of the keywords & codes:
	 * (mpMAP_PROJECTION_DESC is excluded from this list since
	 * it is not treated as a normal projection keyword) */

struct mpKEYWORD_TO_CODE mpKwds_Codes[mpNUMBER_OF_KEYWORDS] = {

  {mpTARGET_NAME,		mpTARGET_NAME_BIT,		mpCHAR,	0},
  {mpTARGET_BODY,		mpTARGET_BODY_BIT,		mpCHAR,	0},
  {mpMAP_PROJECTION_TYPE,	mpMAP_PROJECTION_TYPE_BIT,	mpCHAR,	0},
  {mpCOORDINATE_SYSTEM_NAME,	mpCOORDINATE_SYS_NAME_BIT,	mpCHAR,	0},
  {mpPOSITIVE_LONGITUDE_DIRECTION, mpPOSITIVE_LONGIT_DIR_BIT,	mpCHAR,	0},
  {mpA_AXIS_RADIUS, 		mpA_AXIS_RADIUS_BIT, 		mpDBLE,	0},
  {mpB_AXIS_RADIUS, 		mpB_AXIS_RADIUS_BIT, 		mpDBLE,	0},
  {mpC_AXIS_RADIUS, 		mpC_AXIS_RADIUS_BIT, 		mpDBLE,	0},
  {mpBODY_LONG_AXIS,		mpBODY_LONG_AXIS_BIT,		mpDBLE,	0},
  {mpMINIMUM_LATITUDE,		mpMINIMUM_LATITUDE_BIT,		mpDBLE,	0},
  {mpMAXIMUM_LATITUDE,		mpMAXIMUM_LATITUDE_BIT,		mpDBLE,	0},
  {mpMINIMUM_LONGITUDE,		mpMINIMUM_LONGITUDE_BIT,	mpDBLE,	0},
  {mpMAXIMUM_LONGITUDE,		mpMAXIMUM_LONGITUDE_BIT,	mpDBLE,	0},

  {mpMAP_SCALE,			mpMAP_SCALE_BIT,		mpDBLE,	1},
  {mpMAP_RESOLUTION,		mpMAP_RESOLUTION_BIT,		mpDBLE,	1},
  {mpCENTER_LATITUDE,		mpCENTER_LATITUDE_BIT,		mpDBLE,	1},
  {mpCENTER_LONGITUDE,		mpCENTER_LONGITUDE_BIT,		mpDBLE,	1},
  {mpSPHERICAL_AZIMUTH,		mpSPHERICAL_AZIMUTH_BIT,	mpDBLE,	1},
  {mpCARTESIAN_AZIMUTH,		mpCARTESIAN_AZIMUTH_BIT,	mpDBLE,	1},
  {mpLINE_PROJECTION_OFFSET,	mpLINE_PROJECTION_OFFSET_BIT,	mpDBLE,	1},
  {mpSAMPLE_PROJECTION_OFFSET,	mpSAMPLE_PROJECTION_OFFSET_BIT,	mpDBLE,	1},
  {mpFIRST_STANDARD_PARALLEL,	mpFIRST_STANDARD_PARALLEL_BIT,	mpDBLE,	1},
  {mpSECOND_STANDARD_PARALLEL,	mpSECOND_STANDARD_PARALLEL_BIT,	mpDBLE,	1},

  {mpFOCAL_LENGTH,	 	mpFOCAL_LENGTH_BIT,		mpDBLE,	2},
  {mpFOCAL_PLANE_SCALE,		mpFOCAL_PLANE_SCALE_BIT,	mpDBLE,	2},
  {mpNORTH_ANGLE,		mpNORTH_ANGLE_BIT,		mpDBLE,	2},
  {mpOPT_AXIS_INTERCEPT_LINE,	mpOPT_AXIS_INTERCEPT_LINE_BIT,	mpDBLE,	2},
  {mpOPT_AXIS_INTERCEPT_SAMPLE,	mpOPT_AXIS_INTERCEPT_SAMPLE_BIT,mpDBLE,	2},
  {mpPLANET_CENTER_LINE,		mpPLANET_CENTER_LINE_BIT,	mpDBLE,	2},
  {mpPLANET_CENTER_SAMPLE,	mpPLANET_CENTER_SAMPLE_BIT,	mpDBLE,	2},
  {mpSUB_SPACECRAFT_LATITUDE,	mpSUB_SPACECRAFT_LATITUDE_BIT,	mpDBLE,	2},
  {mpSUB_SPACECRAFT_LONGITUDE,	mpSUB_SPACECRAFT_LONGITUDE_BIT,	mpDBLE,	2},
  {mpTARGET_CENTER_DISTANCE,	mpTARGET_CENTER_DISTANCE_BIT,	mpDBLE,	2},
  {mpSPACECRAFT_DISTANCE,	mpSPACECRAFT_DISTANCE_BIT,	mpDBLE,	2},

};
