C  5 SEP 1994  ...CRI... MSTP S/W CONVERSION (VICAR PORTING)

      INCLUDE 'VICMAIN_FOR'

      SUBROUTINE MAIN44
C  MILUS IMAGE ARITHMETIC ROUTINE  A. ZOBRIST
      IMPLICIT INTEGER(A-Z)
      CHARACTER*16 OUTFORMAT
      INTEGER*2 PIC1(100000), QTABLE(-32768:32767)
      INTEGER*4 TABLE(500), QTABAR(500)
C
      CALL IFMESSAGE('HSTRETCH version 5-SEP-94')
      CALL XVEACTION('SA',' ')

      CALL XVPARM('FORMAT',OUTFORMAT,NVALUE,VALUDF,1)
      CALL XVPARM('VALUE',VALUE,NVALUE,VALUDF,1)
      CALL XVPARM('BVALUE',BVAL,NBVAL,BVALDF,1)
      CALL XVPARM('TABLE',TABLE,NTABL,TABLDF,500)
      CALL XVPARM('QTABLE',QTABAR,NQTAB,QTABDF,500)

C Sanity Check: Must set either TABLE or QTABLE
      IF (QTABDF.EQ.1.AND.TABLDF.EQ.1) THEN
         CALL XVMESSAGE('Must set either TABLE or QTABLE',' ')
         CALL ABEND
         RETURN
      ENDIF

      IF (BVALDF.EQ.0) THEN     ! Initialize table to background
         DO 22 I=-32767,32768
 22      QTABLE(I-1) = BVAL
      ELSE                      ! Initialize table to identity
          DO 1 I=-32767,32768
 1        QTABLE(I-1) = I-1
      ENDIF

      IF(TABLDF.EQ.0) THEN      ! Use TABLE
         DO 33 I=1,NTABL,2
 33      QTABLE(TABLE(I)) = TABLE(I+1)
      ELSE                      ! Use foreground VALUE
         DO 2 I=1,NQTAB
 2       QTABLE(QTABAR(I)) = VALUE
      ENDIF
C
      CALL XVUNIT(RUNIT,'INP',1,STATUS,' ')
      CALL XVOPEN(RUNIT,STATUS,'U_FORMAT','HALF',' ')
      IF (STATUS .NE. 1) CALL XVSIGNAL(RUNIT,STATUS,1)
      IF (OUTFORMAT(1:4).EQ.'SAME') THEN
	CALL XVGET(RUNIT,STATUS,'FORMAT',OUTFORMAT,' ')
      ENDIF
      CALL XVSIZE(SL,SS,NL,NS,NLI,NSI)
      CALL XVUNIT(WUNIT,'OUT',1,STATUS,' ')
      CALL XVOPEN(WUNIT,STATUS,'U_FORMAT','HALF','U_NL',NL,
     +  'U_NS',NS, 'O_FORMAT',OUTFORMAT,'OP','WRITE',' ')
      IF (STATUS .NE. 1) CALL XVSIGNAL(WUNIT,STATUS,1)
      DO 100 I=1,NL
         CALL XVREAD(RUNIT,PIC1,STATUS,'SAMP',SS,
     +      'NSAMPS',NS,'LINE',SL+I-1,' ')
         IF (STATUS .NE. 1) CALL XVSIGNAL(RUNIT,STATUS,1)
         DO 9 J=1,NS
            K = PIC1(J)
            PIC1(J) = QTABLE(K)
   9     CONTINUE
         CALL XVWRIT(WUNIT,PIC1,STATUS,' ')
         IF (STATUS .NE. 1) CALL XVSIGNAL(WUNIT,STATUS,1)
 100  CONTINUE
      CALL XVCLOSE(RUNIT,STATUS,' ')
      CALL XVCLOSE(WUNIT,STATUS,' ')
      RETURN
      END
