      SUBROUTINE DARRAY(MODE,I,J,N,M,S,D)
C   30 JULY 1993...DDK...PORTED TO UNIX
C   21 OCTOBER 1975...JBS...CHANGES FOR CONVERSION TO 360/OS
C   6/6/71 JBS61     FROM SCIENTIFIC SUBROUTINE PACKAGE
C
C     PURPOSE . . .
C
C     CONVERT DOUBLE PRECISION DATA ARRAY FROM SINGLE TO
C     DOUBLE DIMENSION OR VICE VERSA.  THIS PROGRAM ALSO HAS
C     THE CAPABILITY OF PACKING AND UNPACKING DOUBLE PRECISION
C     DATA THAT ARE DOUBLE DIMENSION.
C     THIS SUBR. IS THE DOUBLE PRECISION ANALOG OF THE
C     IBM SSP ROUTINE ARRAY.  THE DARRAY CALLING SEQUENCE AND
C     VARIABLES ARE IDENTICAL TO THOSE OF ARRAY EXCEPT THAT
C     THE VARIABLES S AND D IN DARRAY ARE TYPE DOUBLE PRECISION.
C
      INTEGER*4 MODE,I,J,N,M,K,L
      REAL*8 S(I,J),D(N,M)
C
C  TEST TYPE OF CONVERSION
C
      IF (MODE .EQ. 1) GO TO 100
      IF (MODE .GT. 1) GO TO 120
C
C  CONVERT FROM PACKED TO UNPACKED STORAGE
C
100      DO 110 L=1,J
         DO 115 K=1,I
            D(I-K+1,J-L+1)=S(I-K+1,J-L+1)
115      CONTINUE
110      CONTINUE
         GO TO 140
C
C  CONVERT FROM UNPACKED TO PACKED STORAGE
C
120      DO 130 L=1,J
         DO 135 K=1,I
            S(K,L)=D(K,L)
135      CONTINUE
130      CONTINUE
140   RETURN
      END
