      INCLUDE 'VICMAIN_FOR'
C Test of subroutine ABLE97
C 
C History:
C     tlt  Renamed LAB_PREPDUR to LAB_PREPCYCLE
C     tlt  Renamed LAB_READOUTDUR to LAB_READOUTCYCLE
C     ays  Updated to accomodate new vicar property
C          labels
C
      SUBROUTINE MAIN44
      INTEGER UNIT
      INCLUDE 'cas_isslab'          !SETS UP COMMON BLOCK
c      INCLUDE 'cas_isslab.fin'          !REMOVE FOR DELIVERY

      CALL XVUNIT(UNIT,'INP',1,ISTAT,' ')
      CALL XVOPEN(UNIT,ISTAT,' ')
      IF(ISTAT.NE.1)THEN
         CALL XVMESSAGE('***CAN NOT OPEN INPUT',' ')
         CALL ABEND
      ENDIF
	
      CALL ABLE97(IND,UNIT)

      CALL PRINTSTR(7,LAB_LABTYPE,'LABEL TYPE = ')
      CALL PRINTSTR(30,LAB_PHASE,'MISSION PHASE = ')
      CALL PRINTSTR(5,LAB_CAMERA,'CAMERA ID = ')
      CALL PRNT(4,1,LAB_SCLK,'SCLK = ')
      CALL PRNT(4,1,LAB_SCETY,'EVENT TIME YEAR = ')
      CALL PRNT(4,1,LAB_SCETD,'EVENT TIME DAY = ')
      CALL PRNT(4,1,LAB_SCETH,'EVENT TIME HOUR = ')
      CALL PRNT(4,1,LAB_SCETM,'EVENT TIME MINUTE = ')
      CALL PRNT(4,1,LAB_SCETS,'EVENT TIME SECOND = ')
      CALL PRNT(4,1,LAB_SCETMS,'EVENT TIME MSEC = ')
      CALL PRNT(4,1,LAB_SCETY2,'EARTH RECEIVED START TIME YEAR = ')
      CALL PRNT(4,1,LAB_SCETD2,'EARTH RECEIVED START TIME DAY = ')
      CALL PRNT(4,1,LAB_SCETH2,'EARTH RECEIVED START TIME HOUR = ')
      CALL PRNT(4,1,LAB_SCETM2,'EARTH RECEIVED START TIME MINUTE = ')
      CALL PRNT(4,1,LAB_SCETS2,'EARTH RECEIVED START TIME SECOND = ')
      CALL PRNT(4,1,LAB_SCETMS2,'EARTH RECEIVED START TIME MSEC = ')
      CALL PRNT(4,1,LAB_SCETY3,'EARTH RECEIVED STOP TIME YEAR = ')
      CALL PRNT(4,1,LAB_SCETD3,'EARTH RECEIVED STOP TIME DAY = ')
      CALL PRNT(4,1,LAB_SCETH3,'EARTH RECEIVED STOP TIME HOUR = ')
      CALL PRNT(4,1,LAB_SCETM3,'EARTH RECEIVED STOP TIME MINUTE = ')
      CALL PRNT(4,1,LAB_SCETS3,'EARTH RECEIVED STOP TIME SECOND = ')
      CALL PRNT(4,1,LAB_SCETMS3,'EARTH RECEIVED STOP TIME MSEC = ')
      CALL PRNT(4,1,LAB_SCETY4,'START TIME YEAR = ')
      CALL PRNT(4,1,LAB_SCETD4,'START TIME DAY = ')
      CALL PRNT(4,1,LAB_SCETH4,'START TIME HOUR = ')
      CALL PRNT(4,1,LAB_SCETM4,'START TIME MINUTE = ')
      CALL PRNT(4,1,LAB_SCETS4,'START TIME SECOND = ')
      CALL PRNT(4,1,LAB_SCETMS4,'START TIME MSEC = ')
      CALL PRNT(4,1,LAB_SCETY5,'MID TIME YEAR = ')
      CALL PRNT(4,1,LAB_SCETD5,'MID TIME DAY = ')
      CALL PRNT(4,1,LAB_SCETH5,'MID TIME HOUR = ')
      CALL PRNT(4,1,LAB_SCETM5,'MID TIME MINUTE = ')
      CALL PRNT(4,1,LAB_SCETS5,'MID TIME SECOND = ')
      CALL PRNT(4,1,LAB_SCETMS5,'MID TIME MSEC = ')
      CALL PRNT(4,1,LAB_SCLKSTART,'SCLKSTART = ')
      CALL PRNT(4,1,LAB_SCLKSTARTSUB,'SCLKSTARTSUB = ')
      CALL PRNT(4,1,LAB_SCLKSTOP, 'SCLKSTOP = ')
      CALL PRNT(4,1,LAB_SCLKSTOPSUB, 'SCLKSTOPSUB = ')
      CALL PRINTSTR(20,LAB_SWVERS,'IMAGE BUILDER S/W VERSION = ')
      CALL PRINTSTR(4,LAB_MODE,'INSTRUMENT MODE = ')
      CALL PRINTSTR(20,LAB_GAIN,'GAIN STATE/_MODE_ID  = ')
      CALL PRNT(7,1,LAB_EXPOS,'EXPOSURE TIME =')
      CALL PRINTSTR(8,LAB_COMPRSN,'COMPRESSION = ')
      CALL PRINTSTR(6,LAB_CONVRSN,'ENCODING/DATA_CONVERSION_TYPE = ')
      CALL PRNT(7,1,LAB_CCDTEMP,'CDD TEMP = ')
      CALL PRNT(7,1,LAB_OPTTEMP,'OPTICS TEMP = ')
      CALL PRNT(7,1,LAB_REAROPTTEMP,'REAR OPTICS TEMP = ')
      CALL PRNT(7,1,LAB_FLTTEMP,'FILTER TEMP = ')
      CALL PRINTSTR(3,LAB_LTFLD,'LIGHT FLOOD STATE = ')
      CALL PRINTSTR(3,LAB_ANTIBLM,'ANTI-BLOOMING STATE = ')
      CALL PRINTSTR(3,LAB_CALLAMP,'CALIBRATION LAMP STATE = ')
      CALL PRNT(4,1,LAB_BLOCKS,'BLOCKS/GROUP = ')
      CALL PRNT(4,1,LAB_ALGORITHM,'ALGORITHM = ')
      CALL PRNT(4,1,LAB_BTYPE,'BLOCK TYPE = ')
      CALL PRNT(4,1,LAB_QFACTOR,'Q FACTOR INDEX = ')
      CALL PRNT(7,1,LAB_COMPRAT,'CMPRSN RATIO = ')
      CALL PRNT(4,1,LAB_MISSING,'MISSING LINES = ')
      CALL PRINTSTR(30,LAB_TARGET,'TARGET_NAME = ')
      CALL PRINTSTR(30,LAB_OBSERVID,'OBSERVATION ID = ')
      CALL PRINTSTR(18,LAB_SOURCE,'ILLUMINANT = ')
      CALL PRNT(7,1,LAB_RADIANCE,'RADIANCE = ')
      CALL PRNT(4,1,LAB_PREPCYCLE,'PREPARE CYCLE INDEX = ')
      CALL PRNT(4,1,LAB_READOUTCYCLE,'READOUT CYCLE INDEX = ')
      CALL PRNT(7,1,LAB_BIAS,'BIAS/BIAS_STRIP_MEAN = ')
      CALL PRNT(7,1,LAB_EXTPIXVAL,'DARK/EXTENDED PIXEL VALUE = ')
      CALL PRNT(7,1,LAB_SENSORTEMP,'SENSOR HEAD ELEC TEMP = ')
      CALL PRNT(7,1,LAB_DATARATE,'INSTRUMENT DATA RATE = ')
      CALL PRINTSTR(8,LAB_SHUTTERMODE,
     1              'SHUTTER MODE (NACONLY/WACONLY/BOTSIM) = ')
      CALL PRINTSTR(3,LAB_DLYREADOUT,'DELAYED READOUT FLAG = ')
      CALL PRINTSTR(21,LAB_IMAGETIME,'IMAGETIME = ')
      CALL PRNT(4,1,LAB_COMPPARAM,'COMPPARAM = ')
      CALL PRNT(4,1,LAB_SCCP,'SPACECRAFT CLOCK CNT PARTITION = ')
      CALL PRNT(4,1,LAB_COMDSEQNUM,'COMMAND SEQUENCE NUMBER = ')
      CALL PRINTSTR(5,LAB_FILTER1,'FILTER_NAME1 = ')
      CALL PRINTSTR(5,LAB_FILTER2,'FILTER_NAME2 = ')
C      CALL PRINTSTR(21,LAB_CMPRSPARAM,'INSTRUMENT_CMPRS_PARAM = ')
      CALL PRINTSTR(9,LAB_MISPACFLG,'MISSING_PACKET_FLAG = ')
      CALL PRINTSTR(10,LAB_SHUTID,'SHUTTER STATE (ENABLED/DISABLED) = ')
      CALL PRINTSTR(21,LAB_ERTSTART,'EARTH_RECEIVED_START_TIME = ')
      CALL PRINTSTR(21,LAB_ERTSTOP,'EARTH_RECEIVED_STOP_TIME = ')
      CALL PRINTSTR(30,LAB_FLTSOFTVERSID,
     1    'FLIGHT_SOFTWARE_VERSION_ID = ')
      CALL PRINTSTR(21,LAB_STARTTIME,'START_TIME = ')
      CALL PRNT(7,1,LAB_CLD,'CALIBRATION_LAMP_DURATION = ')
      CALL PRNT(4,1,LAB_ELBIAS,'ELECTRONIC_BIAS = ')
      CALL PRNT(4,1,LAB_PCVI,'PARALLEL_CLOCK_VOLTAGE_INDEX = ')
      CALL PRNT(4,1,LAB_EXPPACKETS,'EXPECTED_PACKETS = ')
      CALL PRNT(4,1,LAB_RECPACKETS,'RECEIVED_PACKETS = ')
      CALL PRNT(4,1,LAB_ORDERNUM,'ORDER_NUMBER = ')
      CALL PRNT(4,1,LAB_SEQNUM,'SEQUENCE_NUMBER = ')
      CALL PRNT(4,1,LAB_VALIDMAX,'VALID_MAXIMUM = ')
      CALL PRNT(4,1,LAB_VALIDMAXFW,'VALID_MAXIMUM (FULL WELL) = ')
      CALL PRNT(7,1,LAB_EXPMAX,'EXPECTED_MAXIMUM (% DN) = ')
      CALL PRNT(7,1,LAB_EXPMAXFW,'EXPECTED_MAXIMUM (% FULL WELL) = ')
      CALL PRNT(7,1,LAB_COMPRATEPRED,'INST_CMPRS_RATE (PREDICTED) = ')
      CALL PRNT(7,1,LAB_COMPRATEACT,'INST_CMPRS_RATE (ACTUAL) = ')
      CALL PRINTSTR(40,LAB_DSID,'DATA_SET_ID = ')
      CALL PRINTSTR(15,LAB_IHN,'INSTRUMENT_HOST_NAME = ')
      CALL PRINTSTR(38,LAB_IN,'INSTRUMENT_NAME = ')
      CALL PRINTSTR(100,LAB_NOTE,'NOTE = ')
      CALL PRINTSTR(21,LAB_PCTIME,'PRODUCT_CREATION_TIME = ')
      CALL PRINTSTR(40,LAB_PRID,'PRODUCT_ID = ')
      CALL PRINTSTR(11,LAB_PVT,'PRODUCT_VERSION_TYPE = ')
      CALL PRINTSTR(30,LAB_SID,'SEQUENCE_ID = ')
      CALL PRINTSTR(120,LAB_CMDNAME,'COMMAND_FILE_NAME = ')
      CALL PRINTSTR(15,LAB_IMGOBSTYPE(1),
     1     'IMAGE_OBSERVATION_TYPE = ')
      DO I=2,5
         CALL PRINTSTR(15,LAB_IMGOBSTYPE(i),
     1     '                       = ')
      END DO
      CALL PRINTSTR(60,LAB_SEQTITLE,'SEQUENCE_TITLE = ')
      CALL PRINTSTR(21,LAB_MIDTIME,'IMAGE_MID_TIME = ')
      CALL PRINTSTR(250,LAB_DESCRIPTION,'DESCRIPTION = ')
      CALL PRINTSTR(100,LAB_METHODDESC,'METHOD_DESC = ')
      CALL PRINTSTR(75,LAB_TARGETDESC,'TARGET_DESC = ')
      CALL PRINTSTR(30,LAB_TARGETLIST(1),'TARGET_LIST = ')
      DO I=2,10
         CALL PRINTSTR(30,LAB_TARGETLIST(i),'            = ')
      END DO
      CALL PRINTSTR(10,LAB_TELEMID,'TELEMETRY_FORMAT_ID = ')
 
C
      CALL PRNT(4,1,IND,'IND = ')

C..REPEAT TEST FROM C
      CALL XVMESSAGE(
     . 'Repeat a test case in C to test C interface:', ' ')

      CALL TZABLE97(UNIT)
      RETURN
      END

      SUBROUTINE PRINTSTR( LENGTH, STR, TITLE)
C
C      SUBSTITUTE FOR prnt for DCODE=99.  PRNT does not handle CHARACTER.

      CHARACTER STR*(*), TITLE*(*)
      CHARACTER*249 PBUF
C      Can handle maximum of 249 characters (Len STR + Len TITLE <249) 
C==================================================================
      L = LEN(TITLE)

C...Find the last non-blank character
      DO I=LENGTH,1,-1
        ILENGTH = I
        IF (STR(I:I) .NE. ' ') GOTO 100
      END DO

100   LLAST = L + ILENGTH
      IF (LLAST .GE. 250) THEN
         CALL XVMESSAGE(TITLE, ' ')
         CALL XVMESSAGE(STR(1:ILENGTH), ' ')
      ELSE
         PBUF(1:L) = TITLE
         PBUF(L+1:MIN(LLAST,249)) = STR          ! CONCATENATE
         CALL XVMESSAGE(PBUF(1:MIN(LLAST,249)), ' ')
      ENDIF
      RETURN
      END
