      INCLUDE 'VICMAIN_FOR'
      SUBROUTINE MAIN44
C  THIS IS A TEST PROGRAM FOR SUBROUTINE ITER.  
C  ITER PROVIDES ITERATIVE CONVERGENCE FOR OBLATE
C  PLANETS FOR SUBROUTINE TRANV.   IN THE TEST PROGRAM
C  PROGRAM THE RADIAL ECCENTRICITY (EPS) VARIES FROM
C  .1D0 TO .9DO.

	DOUBLE PRECISION PI, CHI, PHI, EPS
	PI = 3.141592653589D0
	CHI = PI/4.D0
        EPS = .1D0
	DO 10 I = 1,9
	   CALL PRNT(8,1,EPS,'ECCENTRICITY = .')
           CALL ITER(CHI,PHI,EPS,PI)
	   CALL PRNT(8,1,PHI,'         PHI = .')
	   CALL XVMESSAGE(' ',' ')
           EPS = EPS + .1D0
 10	CONTINUE
	RETURN
	END
