	INCLUDE 'VICMAIN_FOR'
C
C  89-06-24 ...REA...  new program
C  91-05-01 ...REA...  convert to UNIX/VICAR
C  01-02-08 ...REA...  remove screen printing debris 
C
	SUBROUTINE MAIN44
C
	COMMON /RAWFIL/FILTER,WVLEN
	REAL*4 FILTER(158,6),WVLEN(158),CWAVE(6)
	CHARACTER*80 BUF
C					                      process parameters
	CALL XVPARM('DATE',JDATE,ICNT,IDEF,0)
	CALL XVPARM('ADJUST',IADJ,ICNT,IDEF,0)
C							  get response functions
	CALL CENTWAV(JDATE,CWAVE)
C								  print them out
	DO I=1,158
	    WRITE (BUF,100) WVLEN(I),(FILTER(I,J),J=1,6)
  100	    FORMAT(F7.3,'   ',6F10.4)
	    CALL XVMESSAGE(BUF,' ')
	END DO
C							  Plot the TIMS brothers
	CALL PLOTXY(FILTER,WVLEN,JDATE)
C						   Print out central wavelengths
	WRITE (BUF,200) (CWAVE(I),I=1,6)
  200	FORMAT(' Central wavelengths are:',6F7.3)
	CALL XVMESSAGE(BUF,' ')
C
	RETURN
	END
C**********************************************************************
C
	SUBROUTINE PLOTXY(FILTER,WVLEN,JDATE)
C
	REAL FILTER(158,6),WVLEN(158)
	CHARACTER*80 MSG,MSG2,MSG3,MSG4,MSG5
C
	NUM = 158
	XLO = 7.5
	XHI = 12.5
	YLO = 0.0
	YHI = 1.0
	NXTIC = 10
	NYTIC = 10
C							create PostScript file
	WRITE (MSG4,100) JDATE,CHAR(0)
  100	FORMAT(' Calibration in effect on ',I8,A1)
	MSG  = 'Microns' // CHAR(0)
	MSG2 = 'Response' // CHAR(0)
	MSG3 = 'TIMS Response Functions' // CHAR(0)
	MSG5 = ' ' // CHAR(0)
	CALL PSPLOT(WVLEN,FILTER(1,1),NUM,XLO,XHI,YLO,YHI,NXTIC,
     +		NYTIC,MSG,MSG2,MSG3,MSG4,MSG5,0)
	CALL PSPLOT(WVLEN,FILTER(1,2),NUM,XLO,XHI,YLO,YHI,-1,-1,
     +		MSG,MSG2,MSG3,MSG4,MSG5,0)
	CALL PSPLOT(WVLEN,FILTER(1,3),NUM,XLO,XHI,YLO,YHI,-1,-1,
     +		MSG,MSG2,MSG3,MSG4,MSG5,0)
	CALL PSPLOT(WVLEN,FILTER(1,4),NUM,XLO,XHI,YLO,YHI,-1,-1,
     +		MSG,MSG2,MSG3,MSG4,MSG5,0)
	CALL PSPLOT(WVLEN,FILTER(1,5),NUM,XLO,XHI,YLO,YHI,-1,-1,
     +		MSG,MSG2,MSG3,MSG4,MSG5,0)
	CALL PSPLOT(WVLEN,FILTER(1,6),NUM,XLO,XHI,YLO,YHI,-1,-1,
     +		MSG,MSG2,MSG3,MSG4,MSG5,-1)
C
	RETURN
	END
