int mat33_mat33_mult(double *A, double *B, double *C);
double mat33_det(double *A);
int mat33_add(double *A, double *B, double *C);
int mat33_inverse(double *A, double *B);
int mat33_assign(double *A, double a0, double a1, double a2, double a3, double a4, double a5, double a6, double a7, double a8);
int mat33_print(double *A);
int mat33_copy(double *A, double *B);
int mat33_transpose(double *A, double *B);
double mat33_xtax(double *X, double *A);
double mat33_xtay(double *X, double *A, double *Y);
int mat33_vec31_mult(double *A, double *V, double *B);
int vec31_add(double *A, double *B, double *C);
int vec31_assign(double *V, double v0, double v1, double v2);
int vec31_copy(double *A, double *B);
int vec31_subtract(double *A, double *B, double *C);
int mat33_scale(double *A, double s, double *B);
int vec31_print(double *A);
int vec31_scale(double *A, double s, double *B);
int vec31_axpy(double a, double *X, double *Y, double *Z);
double vec31_vec31_dot(double *A, double *B);
int vec31_vec31_cross(double *A, double *B, double *C);
double vec31_norm(double *A);
int vec31_unit(double *A);
int vec31_vec31_basis(double *A, double *B, double *C);
