/******************************************************************************

MOKEYWORDS.H	
Include file for MIPS Mars Observer Systematic Software

Purpose

Defines all PDS keywords and MO defined keywords that are used in the MIPS
MO Systematic Software. 

*******************   For all MO application programmers   ******************

Use the defined names "moPDS_KEYWORD" instead of the actual keyword 
throughout your source code. This include file allows for errors to be found
during compilation of software; thus errors are located BEFORE run-time.

*****************************************************************************

Author		Justin McNeill, Jr (JFM059)
Date		August 1993
Revisions	Original

*/

/*

KEYWORD NAMES FOR FILE CHARACTERISTICS

*/

#define 	moPDS_VERSION_ID		"PDS_VERSION_ID"
#define 	moFILE_SPECIFICATION_NAME	"FILE_SPECIFICATION_NAME"
#define		moRECORD_TYPE			"RECORD_TYPE"
#define		moRECORD_BYTES			"RECORD_BYTES"
#define		moFILE_RECORDS			"FILE_RECORDS"
#define		moLABEL_RECORDS			"LABEL_RECORDS"

/*

KEYWORD NAMES FOR OBJECTS AND THEIR CHARACTERISTICS

*/

#define		moTABLE				"TABLE"

#define		moRAW_IMAGE_HISTOGRAM		"RAW_IMAGE_HISTOGRAM"

#define		moIMAGE				"IMAGE"

#define		moITEMS				"ITEMS"
#define		moITEM_BYTES			"ITEM_BYTES"
#define		moDATA_TYPE			"DATA_TYPE"

#define		moSAMPLE_TYPE			"SAMPLE_TYPE"
#define		moSAMPLE_BITS			"SAMPLE_BITS"
#define		moSAMPLE_BIT_MASK		"SAMPLE_BIT_MASK"

#define		moLINES				"LINES"
#define		moLINES_SAMPLES			"LINES_SAMPLES"
#define		moSTART_LINE			"START_LINE"
#define		moSTART_SAMPLE			"START_SAMPLE"

/*

KEYWORD NAMES SPECIFIC TO PRODUCTION TABLE AND MASTER INDEX TABLE

*/

#define		moFRAME_ID			"FRAME_ID"
#define		moTILE_ID			"TILE_ID"
#define		moMRPS_ID			"MRPS_ID"
#define		moMASK_TYPE			"MASK_TYPE"

/*

KEYWORD NAMES OF MOC IMAGE ANCILLARY DATA

*/

#define		moSPACECRAFT_NAME		"SPACECRAFT_NAME"
#define		moMISSION_PHASE_NAME		"MISSION_PHASE_NAME"
#define		moTARGET_NAME			"TARGET_NAME"
#define		moINSTRUMENT_NAME		"INSTRUMENT_NAME"
#define		moINSTRUMENT_ID			"INSTRUMENT_ID"
#define		moPRODUCER_ID			"PRODUCER_ID"
#define		moPRODUCT_CREATION_TIME		"PRODUCT_CREATION_TIME"
#define		moSOFTWARE_NAME			"SOFTWARE_NAME"
#define		moUPLOAD_ID			"UPLOAD_ID"
#define		moDATA_SET_ID			"DATA_SET_ID"
#define		moVOLUME_ID			"VOLUME_ID"
#define		moVOLUME_VERSION_ID		"VOLUME_VERSION_ID"
#define		moPRODUCT_ID			"PRODUCT_ID"
#define		moASSOCIATED_PRODUCT_ID		"ASSOCIATED_PRODUCT_ID"
#define		moSTART_TIME			"START_TIME"
#define		moIMAGE_TIME			"IMAGE_TIME"
#define		moSTOP_TIME			"STOP_TIME"
#define		moSPACECRAFT_CLOCK_START_COUNT	"SPACECRAFT_CLOCK_START_COUNT"
#define		moFOCAL_PLANE_TEMPERATURE	"FOCAL_PLANE_TEMPERATURE"
#define		moGAIN_MODE_ID 			"GAIN_MODE_ID"
#define		moOFFSET_MODE_ID		"OFFSET_MODE_ID"
#define		moLINE_EXPOSURE_DURATION	"LINE_EXPOSURE_DURATION"
#define		moDOWNTRACK_SUMMING		"DOWNTRACK_SUMMING"
#define		moCROSSTRACK_SUMMING		"CROSSTRACK_SUMMING"
#define		moEDIT_MODE_ID			"EDIT_MODE_ID"
#define		moFILTER_NAME			"FILTER_NAME"
#define		moEXPOSURE_DURATION		"EXPOSURE_DURATION"
#define		moRATIONALE_DESC		"RATIONALE_DESC"
#define		moTARGET_CENTER_DISTANCE	"TARGET_CENTER_DISTANCE"
#define		moCENTRAL_BODY_DISTANCE		"CENTRAL_BODY_DISTANCE"
#define		moSUB_SPACECRAFT_LATITUDE	"SUB_SPACECRAFT_LATITUDE"
#define		moSUB_SPACECRAFT_LONGITUDE	"SUB_SPACECRAFT_LONGITUDE"
#define		moTWIST_ANGLE			"TWIST_ANGLE"
#define		moRIGHT_ASCENSION		"RIGHT_ASCENSION"
#define		moDECLINATION			"DECLINATION"
#define		moNORTH_AZIMUTH			"NORTH_AZIMUTH"
#define		moSUB_SPACECRAFT_AZIMUTH	"SUB_SPACECRAFT_AZIMUTH"
#define		moHORIZONTAL_PIXEL_SCALE	"HORIZONTAL_PIXEL_SCALE"
#define		moVERTICAL_PIXEL_SCALE		"VERTICAL_PIXEL_SCALE"
#define		moSLANT_DISTANCE		"SLANT_DISTANCE"
#define		moCENTER_LATITUDE		"CENTER_LATITUDE"
#define		moCENTER_LONGITUDE		"CENTER_LONGITUDE"
#define		moUPPER_LEFT_LATITUDE		"UPPER_LEFT_LATITUDE"
#define		moUPPER_LEFT_LONGITUDE		"UPPER_LEFT_LONGITUDE"
#define		moUPPER_RIGHT_LATITUDE		"UPPER_RIGHT_LATITUDE"
#define		moUPPER_RIGHT_LONGITUDE		"UPPER_RIGHT_LONGITUDE"
#define		moLOWER_LEFT_LATITUDE		"LOWER_LEFT_LATITUDE"
#define		moLOWER_LEFT_LONGITUDE		"LOWER_LEFT_LONGITUDE"
#define		moLOWER_RIGHT_LATITUDE		"LOWER_RIGHT_LATITUDE"
#define		moLOWER_RIGHT_LONGITUDE		"LOWER_RIGHT_LONGITUDE"
#define		moSOLAR_DISTANCE		"SOLAR_DISTANCE"
#define		moSUB_SOLAR_LATITUDE		"SUB_SOLAR_LATITUDE"
#define		moSUB_SOLAR_LONGITUDE		"SUB_SOLAR_LONGITUDE"
#define		moSUB_SOLAR_AZIMUTH		"SUB_SOLAR_AZIMUTH"
#define		moINCIDENCE_ANGLE		"INCIDENCE_ANGLE"
#define		moEMISSION_ANGLE		"EMISSION_ANGLE"
#define		moPHASE_ANGLE			"PHASE_ANGLE"
#define		moLOCAL_HOUR_ANGLE		"LOCAL_HOUR_ANGLE"
#define		moCALIBRATION_FILE_NAME		"CALIBRATION_FILE_NAME"
#define		moSOURCE_PRODUCT_ID		"SOURCE_PRODUCT_ID"
#define		moPROCESSING_HISTORY_TEXT	"PROCESSING_HISTORY_TEXT"
#define		moSAMPLE_BITS			"SAMPLE_BITS"
#define		moCHECKSUM			"CHECKSUM"
#define		moSTRETCHED_FLAG		"STRETCHED_FLAG"
#define		moSTRETCH_MINIMUM		"STRETCH_MINIMUM"
#define		moSTRETCH_MAXIMUM 		"STRETCH_MAXIMUM"
