/*
 * NIMSLABEL2.H  -- this defines the names of label items that
 * are generated by NIMSCMM2 and read by VISIS2
 *
 * Note that map projection parameters are written in standard
 * Vicar format, see subroutine MAPLABV2.
 *
 *  09dec94 --lwk-- revised from NIMS_LABEL2.H for GLL phase 2
 *  03nov96 --lwk-- added PSHIFT & THRESHVAL
 *  28sep97 --lwk-- added SUPPNOTE
 *  26nov97 --lwk-- added MAXDISTOR
 *  14feb99 --lwk-- added AINFL
 *  18may99 --lwk-- added wobble parameters
 *  24feb00 --lwk-- added SC_GAPS and SAT_THRSH items
 */

#define EDRS		"EDRS"		/* multiple files separated by comma */

#define CUBE_SIZE	"CUB_SIZE"	/* projected cube size, for TUBE */

#define PROJECT		"PROJECT"	/* always = "GLL" */

#define INSTRUMENT	"INSTRMNT"	/* always = "NIMS" */

#define PHASE		"PHASE"		/* string, e.g., CRUISE */

#define TARGET		"TARGET"

#define PRODID		"PROD_ID"	/* product id (= cube name) */
#define OBSNAME		"OBSNAME"	/* name of observation */
#define OBSEXT		"OBSEXT"	/* observation extension (if split) */
#define MOSNUM		"MOS_NUM"	/* mosaic number */
#define PRODNOTE	"PRODNOTE"	/* product description */
#define OBSNOTE		"OBSNOTE"	/* observation description */
#define SUPPNOTE	"SUPPNOTE"	/* supplement to OBSNOTE */

#define CAL_FILE	"CAL_FILE"	/* names of NIMS-supplied files */
#define DARK_FILE	"DARK_FIL"
#define SOL_FILE	"SOL_FIL"
#define DEBOOM_FILE	"DBM_FIL"
#define DESPIKE_FILE	"DSPK_FIL"

#define PFM_CK		"PFM_CK"	/* Platform C-kernel */
#define ROT_CK		"ROT_CK"	/* Rotor C-kernel */
#define AACS_FILE	"AACS_FIL"	/* AACS pointing file name */
#define IKERNEL		"IKERNEL"	/* Instrument Kernel */
#define SP_KERNEL	"SPKERNEL"	/* S/c-Planet Kernel */
#define SK_ID		"SK_ID"		/* SPKernel ID (in KDB.GLL) */
#define PC_KERNEL	"PCKERNEL"	/* Planet Constants Kernel */

/* for phase-0 support: */
#define POINT_SOURCE    "POINTSRC"      /* pointing source = AACS / SPICE-CK */

#define ERTDATE_B	"ERTDT_B"	/* ERT dates: 1000*YEAR + DAY */
#define ERTDATE_E	"ERTDT_E"
#define ERTTIME_B	"ERTTM_B"	/* ERT times: 100*HOUR + MINUTE */
#define ERTTIME_E	"ERTTM_E"

#define BEG_SCLK	"BEG_SCLK"	/* Spacecraft time (RIM,MOD91,MOD10) */
#define END_SCLK	"END_SCLK"

#define SC_GAPS		"SC_GAPS"	/* gaps in SCLK parameter to nimscmm2 */

#define BEG_SCET	"BEG_SCET"	/* SCET = "YY MMM DD HH:MM:SS" */
#define END_SCET	"END_SCET"

#define B_SSCLAT	"B_SSCLAT"	/* subspacecraft point lat/lon extent */
#define E_SSCLAT	"E_SSCLAT"
#define B_SSCLON	"B_SSCLON"
#define E_SSCLON	"E_SSCLON"

#define B_SSOLLAT	"B_SSLLAT"	/* subsolar point lat/lon extent */
#define E_SSOLLAT	"E_SSLLAT"
#define B_SSOLLON	"B_SSLLON"
#define E_SSOLLON	"E_SSLLON"

#define INS_MODE	"INS_MODE"	/* FULL MAP, LONG MAP, etc. */
#define STOP_SLIDE	"STOPSLID"

#define CAL_TYPE	"CAL_TYPE"	/* calibration = NOCAL,RAD,IOF,BOTH */
#define CAL_BREAK	"CALBREAK"	/* if BOTH, break detector # */
#define SOLAR_FLUX	"SOLAR_F"	/* if IOF, F(sun) */
#define RAD_SENS	"RAD_SENS"	/* radiometric sensitivities */
#define DRK_AVE		"DRK_AVE"	/* ave. dark values */
#define RAD_CONV	"RAD_CONV"	/* conversion factor DN-to-RAD */
#define RAD_BASE	"RAD_BASE"	/* offset for DN-to-RAD conversion */
#define DARK_TYPE	"DARK_TYP"	/* dark update NOUPDATE,PREVVAL,NEARVAL,
					    INTERP */

#define PSHIFT		"PSHIFT"	/* from Cal file */
#define AINFL		"AINFL"
#define THRESHVAL	"THRSHVAL"	/* array from EDR */

#define PHOT_FUNC	"PHOT_FNC"	/* = NOPCOR,LAMBERT,MINNAERT */
#define PHOT_CUT	"PHOT_CUT"	/* cutoff wavelength for phot.fcn. */
#define MINN_EXP	"MINN_EXP"	/* exponent for Minnaert */

#define SLEW_TOL	"SLEW_TOL"	/* slew rate tolerance */
#define SLEW_RATE	"SLEWRATE"	/* ave. slew rate */

#define EQRAD_FUDG	"ERAD_EXP"	/* expanded eq.radius */

#define SUN_AZI		"SUNAZ"		/* azimuth of sun in planet coord's */
#define SC_AZI		"SCAZ"		/* azimuth of s/c in planet coord's */

#define INCI_ANG	"INCI_ANG"	/* photometric angles */
#define EMIS_ANG	"EMIS_ANG"
#define PHAS_ANG	"PHAS_ANG"

#define MIN_LAT		"MINLAT"	/* lat/long range in cube */
#define MIN_LON		"MINLON"
#define MAX_LAT		"MAXLAT"
#define MAX_LON		"MAXLON"

#define MIN_RANGE	"MINRANGE"	/* s/c - planet distance */
#define MAX_RANGE	"MAXRANGE"

#define MIN_SUN_D	"MINSUN_D"	/* s/c - sun distance */
#define MAX_SUN_D	"MAXSUN_D"

#define MIN_CB_D	"MIN_CB_D"	/* s/c - central body distance */
#define MAX_CB_D	"MAX_CB_D"

#define FILL_SIZE	"FILL_SIZ"	/* parameters for FILL algorithm */
#define FILL_NUM	"FILL_NUM"

#define BINNING		"BINNING"	/* = FOOTPRINT or NEAREST */
#define THRESH		"THRESHLD"	/* threshold for FOOTPRINT */
#define FPGRID		"FPGRID"	/* grid size for FOOTPRINT */
#define MAXDISTOR	"MAXDSTOR"	/* max.distortion for FOOTPRINT */

#define DPOINT		"DPOINT"	/* pointing offset correction */
#define DPT_SCLK	"DPT_SCLK"	/* SCLK range for DPOINT */

#define WAMP		"WAMP"		/* pointing wobble parameters */
#define WFREQ		"WFREQ"
#define WPHASE		"WPHASE"
#define WCONE		"WCONE"

#define GRATING_OFFSET	"G_OFFSET"
#define GRATING_START	"G_START"
#define GRATING_DELTA	"G_DELTA"
#define GRATING_STEPS	"G_STEPS"

#define GAIN_STATE	"GAIN"
#define CHOPPER_MODE	"CHOP_MOD"

#define WAVELENGTHS	"WAVLNTHS"

#define B_MASK		"BND_MASK"

#define T_FOCAL		"T_FOCAL_"	/* TEMPERATURES */
#define T_RAD_SHIELD	"T_RADIAT"
#define T_TELESCOPE	"T_TELESC"
#define T_GRATING	"T_GRATIN"
#define T_CHOPPER	"T_CHOPPE"
#define T_ELECTRONICS	"T_ELECTR"

#define SATURATED	"SATURATD"	/* = FLAGGED or NOT_FLGD */
#define SATTHRSH	"SATTHRSH"	/* threshold weight to flag sat. */

#define GEO_STD_DEV	"GEO_SDEV"	/* standard deviation band #s */
#define DN_STD_DEV	"DN_SDEV"

#define LAT_TYPE	"LATITUDE_TYPE"
