C SUBROUTINE TO GET PHYSICAL MEMORY SIZE
        SUBROUTINE GET_MEM_SIZE(MEMSIZE,SAMP,CODE)
        INTEGER MEMSIZE
	INTEGER SAMP, CODE			  ! DUMMY VARIABLES
        REAL    PMEMORY
		CALL XVPARM('PMEM',PMEMORY,I,K,0) ! GET AMOUNT OF PHYSICAL MEMORY.
        MEMSIZE = PMEMORY*1024*1024       ! CONVERT MEGABYTES TO BYTES
        RETURN
        END
