C TEST SUBROUTINE testos
C
      INCLUDE 'VICMAIN_FOR'
      SUBROUTINE MAIN44
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     THIS IS A TEST FOR MODULE testos   C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      CALL TESTOS(IOS)
      IF (IOS .EQ. 0) CALL XVMESSAGE('THE OS IS VMS',' ')
      IF (IOS .EQ. 1) CALL XVMESSAGE('THE OS IS UNIX',' ')
      IF (IOS .EQ. 2) CALL XVMESSAGE('THE OS IS other',' ')

      RETURN
      END

