!
!     This is the test program for EXTRAP
!
      INCLUDE 'VICMAIN_FOR'
      SUBROUTINE MAIN44
C-----THIS IS A TEST PROGRAM FOR MODULE  EXTRAP
C-----EXTRAP WILL CALCULATE VALUES FOR THE DNS OF A LINE SEGMENT
C-----BASED ON THE VALUES OF OTHER POINTS IN THE PICTURE.
C-----THESE OTHER POINTS ARE STORED IN ARRAY PTS.
C-----THIS PROGRAM ASSUMES THAT AN 8 X 8 IMAGE IS INPUT.
C-----EXTRAP IS BEING TOLD TO INTERPOLATE OVER THE AREA
C-----(4,4,3,3)
        INTEGER*4 IUNIT,OUNIT1,OUNIT2,NL,NS
	INTEGER*2 LINE(20)
	INTEGER*2 PTS(48)/3,3,5,4,3, 6,5,3, 7,6,3, 8,7,3, 9,
     .			  3,4,6,                     7,4,10,
     .			  3,5,7,                     7,5,11,
     .			  3,6,8,                     7,6,12,
     .			  3,7,9,4,7,10,5,7,11,6,7,12,7,7,13/
C
	MAX1 = 25
	MAX2 = 10000000

C          OPEN INPUT DATA SET
      CALL XVUNIT(IUNIT,'INP',1,STAT,' ')
      CALL XVOPEN(IUNIT,STAT,'U_FORMAT','HALF',' ')
      CALL XVGET(IUNIT,STAT,'NL',NL,'NS',NS,' ')
C        OPEN OUTPUT DATA SETS
      CALL XVUNIT(OUNIT1,'OUT',1,STAT,' ')
      CALL XVOPEN(OUNIT1,STAT,'OP','WRITE','U_FORMAT','HALF',
     &            'O_FORMAT','BYTE',' ')
      CALL XVUNIT(OUNIT2,'OUT',2,STAT,' ')
      CALL XVOPEN(OUNIT2,STAT,'OP','WRITE','U_FORMAT','HALF',
     &            'O_FORMAT','BYTE',' ')

      DO L=1,NL
          CALL XVREAD(IUNIT,LINE,STAT,'LINE',L,' ')
          CALL XVWRIT(OUNIT1,LINE,STAT,'LINE',L,'NSAMPS',NS,' ')
          CALL XVWRIT(OUNIT2,LINE,STAT,'LINE',L,'NSAMPS',NS,' ')
      END DO

C        CLOSE OUTPUT DATA SETS AND RE-OPEN FOR UPDATE
      CALL XVCLOSE(OUNIT1,STAT,' ')
      CALL XVCLOSE(OUNIT2,STAT,' ')
      CALL XVOPEN(OUNIT1,STAT,'OP','UPDATE','U_FORMAT','HALF',
     &            'O_FORMAT','BYTE',' ')
      CALL XVOPEN(OUNIT2,STAT,'OP','UPDATE','U_FORMAT','HALF',
     &            'O_FORMAT','BYTE',' ')
C
      DO 20 L=4,6
	   CALL EXTRAP(16,L,4,6,PTS,LINE,MAX1)
           CALL XVWRIT(OUNIT1,LINE,STAT,'LINE',L,
     &                 'SAMP',4,'NSAMPS',3,' ')
	   CALL EXTRAP(16,L,4,6,PTS,LINE,MAX2)
           CALL XVWRIT(OUNIT2,LINE,STAT,'LINE',L,
     &                 'SAMP',4,'NSAMPS',3,' ')
 20   CONTINUE

      CALL XVCLOSE(IUNIT,STAT,' ')
      CALL XVCLOSE(OUNIT1,STAT,' ')
      CALL XVCLOSE(OUNIT2,STAT,' ')

      STOP
      END
