        SUBROUTINE TXTIME()

	CHARACTER*6 TIME_NOW
	CALL XTIME(TIME_NOW)
	CALL XVMESSAGE('The time in HHMMSS format is:',' ')
	CALL XVMESSAGE(' ',' ')
	CALL XVMESSAGE(TIME_NOW,' ')
        RETURN
	END
