C
C ***************** FORTRAN CALLABLE ROUTINE *********************
C
C RETURNS .TRUE. IF |N| IS A POWER OF 2.
C POW IS OPTIONAL ARGUMENT GIVING FIRST POWER OF 2 .GE. |N|.
C  85-5-10  ...LWK...
C  93-7-23  ...DDK...

	INTEGER*2 FUNCTION TWOPOW( N, POW)

	INTEGER*2 N, POW, NN, P, I 

        TWOPOW = 1
	IF (N.EQ.0) RETURN	! IN THIS CASE POW IS UNDEFINED

        NN = ABS(N)

	P = 0
	I = 1
	DO WHILE (I.LT.NN)
	  P = P+1
	  I = 2*I
	ENDDO

	IF (I.NE.NN) TWOPOW = 0

        IF (NN.NE.0) POW = P

	RETURN
	END
