c
      Subroutine INTERG(LTABL,RTABL,ISRES,OSRES,LINRES,ISLIN,OSLIN)
c
C     -------------------------------------------------------------
C  INTERPOLATES TO RETURN LINE OF RESEAUS WITHOUT MISSING MEMBERS
C  RETURN   ISLIN,OSLIN
c
      REAL*4 ISRES(2,1),OSRES(2,1),ISLIN(2,*),OSLIN(2,*),A(16),B(4)
      INTEGER*2 LTABL(1),RTABL(1)
      INTEGER*4 NRES/12/
      IF(LINRES.NE.(LINRES/2)*2) GO TO 20
c
C  FILL IN TWO END RESEAUS ONLY
C  X OR Y = A+BX+CY
C  COPY RESEAUS TO RETURN BUFFERS
c
      CALL MVE(7,22,ISRES(1,LTABL(LINRES)),ISLIN(1,2),1,1)
      CALL MVE(7,22,OSRES(1,LTABL(LINRES)),OSLIN(1,2),1,1)
C
C  CREATE 2 X-TRA OS POSITIONS
c
      OSLIN(1,1)=OSRES(1,LTABL(LINRES))
      OSLIN(2,1)=OSRES(2,LTABL(LINRES-1))
      OSLIN(1,1+NRES)=OSRES(1,RTABL(LINRES))
      OSLIN(2,1+NRES)=OSRES(2,RTABL(LINRES-1))
c
C  COMPUTE FIT BETWEEN 3 CLOSEST RES TO GET X-TRA IS RESEAU
C  LEFT SIDE
c
      N=0
9     N=N+1
      A(4)=OSRES(2,LTABL(LINRES-1))
      A(5)=OSRES(2,LTABL(LINRES))
      A(6)=OSRES(2,LTABL(LINRES+1))
      A(7)=OSRES(1,LTABL(LINRES-1))
      A(8)=OSRES(1,LTABL(LINRES))
      A(9)=OSRES(1,LTABL(LINRES+1))
      DO 10 J=1,3
10    A(J)=1.0
      B(1)=ISRES(N,LTABL(LINRES-1))
      B(2)=ISRES(N,LTABL(LINRES))
      B(3)=ISRES(N,LTABL(LINRES+1))
      CALL SIMQ(A,B,3,IND)
      IF(IND.NE.0) CALL PRNT(2,1,LTABL(LINRES),' ERROR AT.')
      ISLIN(N,1)=B(1)+B(2)*OSLIN(2,1)+B(3)*OSLIN(1,1)
      IF(N.LT.2) GO TO 9
C
C  RIGHT SIDE
      N=0
8     N=N+1
      A(4)=OSRES(2,RTABL(LINRES-1))
      A(5)=OSRES(2,RTABL(LINRES))
      A(6)=OSRES(2,RTABL(LINRES+1))
      A(7)=OSRES(1,RTABL(LINRES-1))
      A(8)=OSRES(1,RTABL(LINRES))
      A(9)=OSRES(1,RTABL(LINRES+1))
      DO 11 J=1,3
11    A(J)=1.0
      B(1)=ISRES(N,RTABL(LINRES-1))
      B(2)=ISRES(N,RTABL(LINRES))
      B(3)=ISRES(N,RTABL(LINRES+1))
      CALL SIMQ(A,B,3,IND)
      IF(IND.NE.0) CALL PRNT(2,1,RTABL(LINRES),' ERROR AT.')
      ISLIN(N,1+NRES)=B(1)+B(2)*OSLIN(2,1+NRES)+B(3)*OSLIN(1,1+NRES)
      IF(N.LT.2) GO TO 8
      RETURN
20    IF(LINRES.GE.5.AND.LINRES.LE.19) GO TO 21
      CALL MVE(7,24,ISRES(1,LTABL(LINRES)),ISLIN,1,1)
      CALL MVE(7,24,OSRES(1,LTABL(LINRES)),OSLIN,1,1)
      RETURN
C
C  FILL IN MIDDLE OF FRAME RESEAUS
C  X OR Y = A+BX+CY+DXY
C  COPY OVER THOSE RESEAUS WE DO HAVE TO RETURN BUFFERS
21    CALL MVE(7,4,ISRES(1,LTABL(LINRES)),ISLIN(1,1),1,1)
      CALL MVE(7,4,OSRES(1,LTABL(LINRES)),OSLIN(1,1),1,1)
      CALL MVE(7,4,ISRES(1,RTABL(LINRES)-1),ISLIN(1,NRES-1),1,1)
      CALL MVE(7,4,OSRES(1,RTABL(LINRES)-1),OSLIN(1,NRES-1),1,1)
C
C  CREATE X-TRA 8 OS LOCATIONS
      RL=(OSLIN(1,2)+OSLIN(1,NRES-1))/2.
      DO 25 J=1,8
      OSLIN(1,J+2)=RL
25    OSLIN(2,J+2)=(OSRES(2,LTABL(LINRES-1)+J)+OSRES(2,LTABL(LINRES-1)
     *  +J+1))/2.
C
C  COMPUTE FIT FOR 4 CLOSEST RESEAUS TO GET X-TRA IS LOCATIONS
      DO 30 L=1,8
      N=0
29    N=N+1
      DO 27 J=1,4
27    A(J)=1.0
      A(5)=OSRES(2,LTABL(LINRES-1)+L)
      A(6)=OSRES(2,LTABL(LINRES-1)+L+1)
      A(7)=OSRES(2,LTABL(LINRES+1)+L)
      A(8)=OSRES(2,LTABL(LINRES+1)+L+1)
      A(9)=OSRES(1,LTABL(LINRES-1)+L)
      A(10)=OSRES(1,LTABL(LINRES-1)+L+1)
      A(11)=OSRES(1,LTABL(LINRES+1)+L)
      A(12)=OSRES(1,LTABL(LINRES+1)+L+1)
      A(13)=A(5)*A(9)
      A(14)=A(6)*A(10)
      A(15)=A(7)*A(11)
      A(16)=A(8)*A(12)
      B(1)=ISRES(N,LTABL(LINRES-1)+L)
      B(2)=ISRES(N,LTABL(LINRES-1)+L+1)
      B(3)=ISRES(N,LTABL(LINRES+1)+L)
      B(4)=ISRES(N,LTABL(LINRES+1)+L+1)
      CALL SIMQ(A,B,4,IND)
      IF(IND.NE.0) CALL PRNT(2,1,LTABL(LINRES-1)+L,' ERROR AT.')
      ISLIN(N,L+2)=B(1)+B(2)*OSLIN(2,L+2)+B(3)*OSLIN(1,L+2)+
     *   B(4)*OSLIN(2,L+2)*OSLIN(1,L+2)
      IF(N.LT.2) GO TO 29
30    CONTINUE
      RETURN
      END
