C  THEXCON IS THE FORTRAN PROGRAM THAT TEST THE FORTRAN CALLABLE PORTION
C  OF THE HEXCON SUBROUTINE.

      SUBROUTINE THEXCON()

      INCLUDE 'fortport'

      BYTE IBUF(256) 
      CHARACTER MSG*100
      CHARACTER OBUF*512
      INTEGER*4 I,J

      DO I=1,256
          IBUF(I)=INT2BYTE(I-1)
      ENDDO

      CALL HEXCON(IBUF,OBUF,256)

      DO J=1,512,32
          WRITE(MSG,100) OBUF(J:J+31)
          CALL XVMESSAGE(MSG,' ')
100       FORMAT(A32)
      ENDDO

      END
