	INCLUDE 'VICMAIN_FOR'
	SUBROUTINE MAIN44
C
	REAL RAD(128,128),TEMP(128),WVLEN(128)
	INTEGER*2 TBUF(128),EBUF(128,128)
C						Open datasets, get size field
	CALL XVEACTION('SA',' ')
	CALL XVUNIT(IN,'INP',1,ISTAT,' ')
	CALL XVOPEN(IN,ISTAT,'U_FORMAT','REAL',' ')
	CALL XVSIZE(ISL,ISS,NL,NS,NLIN,NSIN)
	CALL XVUNIT(IOUT,'OUT',1,ISTAT,' ')
	CALL XVOPEN(IOUT,ISTAT,'U_FORMAT','HALF','O_FORMAT','HALF',
     &	           'OP','WRITE','U_ORG','BIL','U_NL',NL,'U_NS',NS,' ')
	CALL XVUNIT(IOUT2,'OUT',2,ISTAT,' ')
	CALL XVOPEN(IOUT2,ISTAT,'U_FORMAT','HALF','O_FORMAT','HALF',
     &	  'OP','WRITE','U_NB',1,'U_ORG','BSQ','U_NL',NL,'U_NS',NS,' ')
C
C						Get the other parameters
	CALL XVPARM('KEY',KEY,NUM,IDEF,0)
	KEY = 129 - KEY
	CALL XVPARM('EMIS',EMIS,NUM,IDEF,0)
	CALL XVPARM('DATE',IDATE,NUM,IDEF,0)
	CALL GET_SEBASS_WAVLEN(IDATE,WVLEN)
C						Update label
	CALL XLADD(IOUT,'HISTORY','LBL1','Emissivity Image',ISTAT,
     &		   'FORMAT','STRING',' ')
	CALL XLADD(IOUT,'HISTORY','LBL2','DN = 10,000*Emissivity',
     &		   ISTAT,'FORMAT','STRING',' ')
	CALL XLADD(IOUT2,'HISTORY','LBL1','Ground Temperature Image',
     &			ISTAT,'FORMAT','STRING',' ')
	CALL XLADD(IOUT2,'HISTORY','LBL2',
     &		  'DN = 100*Degrees Celsius',ISTAT,
     &		  'FORMAT','STRING',' ')
C
	DO ILINE=ISL,ISL+NL-1
	    DO ICHAN=1,128
		CALL XVREAD(IN,RAD(1,ICHAN),ISTAT,'LINE',ILINE,
     &			    'BAND',ICHAN,'SAMP',ISS,'NSAMPS',NS,' ')
	    END DO
	    DO J=1,NS
		DO K=1,128
		    TEMP(K) = PLKINV(WVLEN(K),0.001*RAD(J,K)/EMIS)
		END DO
		CALL SORTR(TEMP,128)
		XTEMP = TEMP(KEY)
		ITEMP = NINT(100.0*(XTEMP-273.15))
		TBUF(J) = MIN(32767,MAX(-32768,ITEMP))
		DO K=1,128
		    XRAD = 1000.0*PLANCK(WVLEN(K),XTEMP)
		    XEMIS = RAD(J,K) / XRAD
		    IEMIS = NINT(10000*XEMIS)
		    EBUF(J,K) = MIN(32767,MAX(-32768,IEMIS))
		END DO
	    END DO
	    DO ICHAN=1,128
		CALL XVWRIT(IOUT,EBUF(1,ICHAN),ISTAT,' ')
	    END DO
	    CALL XVWRIT(IOUT2,TBUF,ISTAT,' ')
	END DO
C
	RETURN
	END
