       PROGRAM  GETLOC
C#######################################################################
C  NAME OF ROUTINE
C      GETLOC ( GET LOCation)
C
C  PURPOSE
C      THIS IS THE STANDARD MAIN PROGRAM USED FOR TAE/VICAR PROGRAMS.
C      THIS MODULE CALLS SUBROUTINE MAIN44 TO ENTER INTO THE BODY OF THE
C      PROGRAM.
C      Program GETLOC is a VICAR applications program which is used to 
C      extract a subarea from a tiepoint file containing theodolite 
C      measurements of grid intersections.  
C  PREPARED FOR USE ON MIPL SYSTEM BY
C      STEVE POHORSKY   INFORMATICS GENERAL CORPORATION    SEPTEMBER 1984
C  FOR
C      MIPL SOFTWARE DEVELOPMENT
C
C  ORIGINAL GETLOC PROGRAM BY
C      GARY YAGI
C
C  ENVIRONMENT
C      VAX 11/780    VMS  with TAE/VICAR2 EXECUTIVE       FORTRAN-77
C     
C  REVISION HISTORY
C    10-94  AS   (CRI) MSTP S/W CONVERSION (VICAR PORTING)
C     4-86  SP   CONVERTED TO USE VICAR2 CALLS.
C     9-84  SP   CONVERTED FROM IBM VICAR VERSION
C     9-84  SP   CHANGED MVE CALL TO USE DCODE OF 7.  DCODE OF 8 DOES  NOT
C                WORK WHEN THE LINE COORDINATE IS 0.0
C  PROGRAM LIMITATIONS
C      SEE HLP FILE.
C  SUBROUTINES CALLED
C      MAIN44
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

        INCLUDE 'VICMAIN_FOR'
      SUBROUTINE MAIN44 
C#######################################################################
C  NAME OF ROUTINE
C     MAIN44 (name for top level subroutine by VICAR convention)
C
C  PURPOSE
C      MAIN44 is used to extract a subarea from a tiepoint 
C      file containing theodolite measurements of grid intersections.  
C  CONVERTED FOR USE ON MIPL SYSTEM BY   
C      STEVE POHORSKY   INFORMATICS GENERAL CORPORATION     SEPTEMBER 1984
C  FOR
C      MIPL SOFTWARE DEVELOPMENT
C  ENVIRONMENT
C      VAX 11/780    VMS  with TAE/VICAR EXECUTIVE       FORTRAN-77
C  CALLING SEQUENCE
C      Standard subroutine call and return.
C  CALLED BY
C      GETLOC
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      IMPLICIT INTEGER(A-Z)
      REAL*8 BUF(27,27),OBUF(729)
C
C======================START OF EXECUTABLE CODE======================

C..OPEN INPUT FILE

      CALL IFMESSAGE('GETLOC version 31-OCT-94')
      CALL XVEACTION('SA',' ')
      CALL XVUNIT(IUNIT,'INP',1,ISTAT,' ')
      IRETURN = 1
      CALL XVSIGNAL(IUNIT, ISTAT, IRETURN)
      CALL XVOPEN(IUNIT,ISTAT, 'OP', 'READ',' ')

C..READ THE SR,SC,NR,NC PARAMETERS.

      CALL XVPARM('SR',SR,ICOUNT,IDEF,1)
      CALL XVPARM('SC',SC,ICOUNT,IDEF,1)
      CALL XVPARM('NR',NR,ICOUNT,IDEF,1)
      CALL XVPARM('NC',NC,ICOUNT,IDEF,1)

      NLOC = NR*NC
      NLO = 1
      NSO = 2*NLOC

C..OPEN THE OUTPUT FILE.

      CALL XVUNIT(OUNIT,'OUT',1,ISTAT,' ')
      IRETURN = 1
      CALL XVSIGNAL(OUNIT, ISTAT, IRETURN)
      CALL XVOPEN(OUNIT, ISTAT, 'OP','WRITE', 'U_NL',NLO,
     .        'U_NS',NSO, 'U_FORMAT','REAL', 'O_FORMAT','REAL',' ')

C..EXTRACT THE SUBAREA OF THE INPUT FILE.

      CALL XVREAD( IUNIT, BUF, ISTAT,' ')

      K = 1
C
      DO I=1,NR
        CALL MVE(7,2*NC,BUF(SC,SR+I-1),OBUF(K),1,1)
        K = K + NC
      END DO
C
      CALL XVWRIT( OUNIT, OBUF, ISTAT,' ' )

      CALL XVCLOSE(IUNIT,ISTAT,' ')
      CALL XVCLOSE(OUNIT,ISTAT,' ')

      RETURN
      END
