      SUBROUTINE TBITS
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     THIS IS A TEST FOR MODULE BITS                                 C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      INTEGER*2  H   /-21846/        !HALFWORD INTEGER HEX AAAA
      INTEGER*4  F   /-1431655766/   !FULLWORD INTEGER HEX AAAAAAAA
      INTEGER*4  A(0:31)             !INTEGER ARRAY
      CHARACTER  CARD*80             !PRINT BUFFER

      CALL XVMESSAGE(' ',' ')

      DO I=15,0,-1
         CALL HBITS(H, I, I, A(I))
      ENDDO

      CALL XVMESSAGE(' ',' ')
      CALL XVMESSAGE(' **HALF DATA** HARDWIRED TO 0xAAAA',' ')
      WRITE(CARD, 100) (A(15-I),I=0,15)
      CALL XVMESSAGE(CARD,' ')

      DO I=31,0,-1
         CALL BITS(F, I, I, A(I))
      ENDDO

      CALL XVMESSAGE(' ',' ')
      CALL XVMESSAGE(' **FULL DATA** HARDWIRED TO 0xAAAAAAAA',' ')
      WRITE(CARD, 100) (A(31-I),I=0,31)
      CALL XVMESSAGE(CARD,' ')

      RETURN
 100  FORMAT(32I1)
      END
