      SUBROUTINE CYLCAL(ITYPE,RLAT,RLON,ZC,CPSI,F,FL,REQ,PI,FLAG)
C
C     RETURNS CALCULATED LATITUDE AND LONGITUDE AT
C          DELX SAMPLES,DELZ LINES FROM SAMPLE 1 AT LATITUDE ZERO
C          RLAT=DELX AT ENTRANCE
C             =LATITUDE AT EXIT
C         RLON=DELZ AT ENTRANCE
C           =LONGITUDE AT EXIT
C     CPSI =LONGITUDE OF SAMPLE 1
C     ZC   = LINE OF THE EQUATOR
C     F    = SCAL AT EQUATOR (KM/PIXEL)
C     FL    = POLAR RADIUS (KM)
C     REQ   = EQUATORIAL RADIUS (KM)
C     NOTE THAT DELZ WILL BE NEGATIVE FOR POSITIVE LATITUDE
      REAL*8 RFL,DREQ
      REAL*8 ZDEL ,DRPOLE,RAD,DLAT,DLAT2
      REAL*8 TOL
      DATA   TOL/1.D-7/
C==================================================================
      DRPOLE=DBLE(FL)
      DREQ=DBLE(REQ)
      RFL=DREQ/DRPOLE
      RFL=RFL*RFL
      IF(ITYPE.EQ.2)GO TO 600
100   CONTINUE
      DELX=RLAT-1.
      DELZ=-(RLON-ZC)
C
C     CALCULATE LONGITUDE
      RLON=F*DELX/REQ/PI*180.
      IF(ABS(RLON).GT.360)GO TO 400
      RLON=CPSI-RLON
      RLON=AMOD(360.+RLON,360.)
C
C     CALCULATE LATITUDE
C     WE MUST SOLVE
C     LAT=ARCSIN(X*F/R(LAT))
C     WE WILL ASSUME  THE EQUATORIAL RADIUS
C     AND THEN ITERATE UNTIL CONVERGENCE
C
      ZDEL=DBLE(F*DELZ)
C
C     CHK FOR PT OFF PLANET
      IF(DABS(ZDEL)-DRPOLE)130,120,400
120   CONTINUE
c      LAT=SIGN(90.,DELZ)
      RLAT=SIGN(90.,DELZ)   ! JAM 7-JUL-1985  NO OTHER REFS TO "LAT", MUST BE WRONG
      GO TO 500
130   CONTINUE
      ITER=0
C
C     INITIAL GUESS FOR RADIUS AND LAT
      RAD=DBLE(REQ)
      DLAT=DASIN(ZDEL/RAD)
140   CONTINUE
C
C     CALC LAT AND CHK FOR ITERATION
      RAD=DREQ/(DSQRT(RFL+(1.0D0-RFL)*DCOS(DLAT)**2))
      DLAT2=DLAT
      DLAT=DASIN(ZDEL/RAD)
      IF(DABS(DLAT-DLAT2).LT.TOL)GO TO 160
      ITER=ITER+1
      IF(ITER.LT.100)GO TO 140
      CALL QPRINT(' *** CYLINDRICAL PROJ CONVERGENCE ERROR.',40)
	IZERO=0
      I=1/IZERO
160   CONTINUE
      RLAT=DLAT*180.0D0/ PI
      RETURN
400   RLON=FLAG
      RLAT=FLAG
500   CONTINUE
      RETURN
600   CONTINUE
C
C     GIVEN RLAT/RLON FIND DELX/DELZ
      DELX=REQ*(AMOD(360.-(AMOD(RLON+360.,360.)-CPSI),360.))*PI/180./F
      DELZ=ABS(RLAT)
      IF(DELZ.LT.90.0)GO TO 610
C
C     WE ARE AT THE POLE
      DELZ=SIGN(FL/F,RLAT)
      DELZ=-DELZ
      GO TO 700
610   CONTINUE
C
C     FIND RADIUS AT RLAT
      DLAT=RLAT*PI/180.
      RAD=DREQ/(DSQRT(RFL+(1.0D0-RFL)*DCOS(DLAT)**2))
      DELZ=RAD/F*SIN(RLAT*PI/180.)
      DELZ=-DELZ
700   CONTINUE
      RLAT=DELX+1.
      RLON=DELZ+ZC
      RETURN
      END
