	include 'VICMAIN_FOR'				      
	SUBROUTINE MAIN44
C	THIS PROGRAM CONVERTS IBM HALFWORD TO VAX 16 BIT WORD 
C	-JAM- 5/24/83
C       JHR: CONVERT TO VICAR2 24-JUNE-85
C	REA: EXTEND TO 4-BYTE FORMATS     17-AUG-98
C
	INTEGER*4 OUNIT,STAT,SL,SS,EL
	INTEGER*2 BUF(100000)
	CHARACTER*4 FORMAT
	CHARACTER*3 ORG
	BYTE BBUF(200000),HOLD
	EQUIVALENCE (BUF,BBUF)
C
        CALL XVUNIT(IUNIT,'INP',1,STAT,' ')
        CALL XVOPEN(IUNIT,STAT,'OPEN_ACT','SA','IO_ACT','SA',' ')
        CALL XVUNIT(OUNIT,'OUT',1,STAT,' ')
        CALL XVOPEN(OUNIT,STAT,'OP','WRITE','OPEN_ACT','SA',
     +		    'IO_ACT','SA',' ')
C
        CALL XVSIZE(SL,SS,NLO,NSO,NLI,NSI)
	CALL XVBANDS(ISB,NB,NBI)
	CALL XLGET(IUNIT,'SYSTEM','ORG',ORG,STAT,'FORMAT','STRING',' ')
	CALL XLGET(IUNIT,'SYSTEM','FORMAT',FORMAT,STAT,
     +		   'FORMAT','STRING',' ')
	IF (FORMAT.EQ.'FULL' .OR. FORMAT.EQ.'REAL') THEN
	    NBPP = 4
	ELSE
	    NBPP = 2
	END IF
	EL = SL + NLO - 1
	IEB = ISB + NB - 1
	NBYTES = NBPP*NSO
C
	IF (ORG .EQ. 'BSQ') THEN
	  IF (NBPP .EQ. 2) THEN
	    DO IB=ISB,IEB
		DO IL=SL,EL
		    CALL XVREAD(IUNIT,BUF,STAT,'BAND',IB,'LINE',IL,
     +				'SAMP',SS,'NSAMPS',NSO,' ')
	    	    DO I=1,NBYTES,NBPP
			HOLD = BBUF(I)
			BBUF(I) = BBUF(I+1)
			BBUF(I+1) = HOLD
		    END DO
		    CALL XVWRIT(OUNIT,BUF,STAT,' ')
		END DO
	    END DO
	  ELSE
	    DO IB=ISB,IEB
		DO IL=SL,EL
		    CALL XVREAD(IUNIT,BUF,STAT,'BAND',IB,'LINE',IL,
     +				'SAMP',SS,'NSAMPS',NSO,' ')
	    	    DO I=1,NBYTES,NBPP
			HOLD = BBUF(I)
			BBUF(I) = BBUF(I+3)
			BBUF(I+3) = HOLD
			HOLD = BBUF(I+1)
			BBUF(I+1) = BBUF(I+2)
			BBUF(I+2) = HOLD
		    END DO
		    CALL XVWRIT(OUNIT,BUF,STAT,' ')
		END DO
	    END DO
	  END IF
	ELSE IF (ORG .EQ. 'BIL') THEN
	  IF (NBPP .EQ. 2) THEN
	    DO IL=SL,EL
		DO IB=ISB,IEB
		    CALL XVREAD(IUNIT,BUF,STAT,'BAND',IB,'LINE',IL,
     +				'SAMP',SS,'NSAMPS',NSO,' ')
		    DO I=1,NBYTES,NBPP
			HOLD = BBUF(I)
			BBUF(I) = BBUF(I+1)
			BBUF(I+1) = HOLD
		    END DO
		    CALL XVWRIT(OUNIT,BUF,STAT,' ')
		END DO
	    END DO
	  ELSE
	    DO IL=SL,EL
		DO IB=ISB,IEB
		    CALL XVREAD(IUNIT,BUF,STAT,'BAND',IB,'LINE',IL,
     +				'SAMP',SS,'NSAMPS',NSO,' ')
		    DO I=1,NBYTES,NBPP
			HOLD = BBUF(I)
			BBUF(I) = BBUF(I+3)
			BBUF(I+3) = HOLD
			HOLD = BBUF(I+1)
			BBUF(I+1) = BBUF(I+2)
			BBUF(I+2) = HOLD
		    END DO
		    CALL XVWRIT(OUNIT,BUF,STAT,' ')
		END DO
	    END DO
	  END IF
	ELSE
	    CALL XVMESSAGE(' Only BSQ and BIL orgs are supported',' ')
	    CALL ABEND
	END IF
C
	CALL XVCLOSE(IUNIT,STAT,' ')
	CALL XVCLOSE(OUNIT,STAT,' ')
C
	RETURN
	END
