CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     THIS IS A TEST FOR MODULE TAB                                  C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE TTBL()
      INCLUDE 'fortport'

      CHARACTER  CARD*80             !PRINT BUFFER
      BYTE       B(10)               !BYTE ARRAY
      BYTE       TAB(256)            !LOOKUP TABLE
      INTEGER*4  I,K                 !INITIALIZATION VARIABLES

      DO I=1,256          !INITIALIZE THE LOOKUP TABLE
         K=I-1
         TAB(I) = INT2BYTE(K)
      ENDDO

      TAB(76)  = INT2BYTE(20)    !DN = 75 => 20
      TAB(126) = INT2BYTE(50)    !DN = 125 => 50
      TAB(251) = INT2BYTE(90)    !DN = 250 => 90

      DO I=1,10           !INITIALIZE THE DATA ARRAY
         K=I*25
         B(I) = INT2BYTE(K)
      ENDDO

      K=10

      CALL TBL(B, TAB, K)
      WRITE(CARD, 100) (B(I),I=1,10)
      CALL XVMESSAGE(CARD,' ')

      RETURN
100   FORMAT(10Z4.2)
      END
