#include "xvmaininc.h"
#include "ftnbridge.h"

/************************************************************************/
/* C-Callable Version: zintrpa - fill in missing values in an array	*/
/*				 using linear interpolation.		*/
/************************************************************************

 Arguments of zintrpa:

 ICODE   is the data format of the array

	ICODE		FORMAT
	   1        Unsigned Char
	   2        Short Int
	   4        Int

 NS      is the number of samples to be filled.
 BUF     is the array.
 I1,I2   are the sample values between which the interpolation is to be 
	 performed. upon return, the array BUF will contain NS elements 
	 such that BUF(1)=I1, BUF(NS)=I2, and all intermediate elements 
 	 are generated by interpolating between I1 and I2.		*/

void zintrpa( icode, n, buf, i1, i2)
int icode;		/* integer code for data format		*/
int n;			/* number of samples to be filled	*/
void *buf;			/* array 				*/
int i1;			/* sample values between which inter-	*/
int i2;			/* polation is performed. 		*/

{
FTN_NAME2(intrpa, INTRPA) ( &icode, &n, buf, &i1, &i2);
}
