        INCLUDE 'VICMAIN_FOR'

	SUBROUTINE MAIN44 

	IMPLICIT NONE
	INCLUDE 'pgminc' 	! TAE CONSTANTS & PARAMETERS
	INTEGER  VBLOCK(xprdim)

	INTEGER	UNIT, STATUS, COUNT, TASKDEF
	INTEGER	POS, RESULT, NHIST, N, I
	INTEGER	INSTANCES(1000)
	CHARACTER*8  KEYWORD, TASK, TASKLIST(1000)
	CHARACTER*132	VALUE, LABEL

        CALL IFMESSAGE('LABVFY version 05-SEP-94')

	CALL XVUNIT(UNIT, 'INP', 1, STATUS,' ')
	CALL XVOPEN(UNIT,STATUS,'OPEN_ACT','SA','IO_ACT','SA',' ')


	CALL XVP ('KEYWORD', KEYWORD, COUNT)
	CALL XVPARM ('TASK', TASK, COUNT, TASKDEF,1)
	CALL XVP ('LABEL', LABEL, COUNT)

	N = 132
	DO WHILE (LABEL(N:N) .EQ. ' ')
	    N = N - 1
	ENDDO

	RESULT = 0

	IF (TASKDEF .EQ. 1) THEN
	    NHIST = 1000
	    CALL XLHINFO (UNIT,TASKLIST,INSTANCES,NHIST,STATUS,' ')
	    DO I = 1, NHIST
		CALL XLGET (UNIT, 'HISTORY', KEYWORD, VALUE, STATUS,
     +			'HIST',TASKLIST(I), 'INSTANCE',INSTANCES(I),
     +                  'FORMAT','STRING',' ' )
		IF (STATUS .EQ. 1) THEN
		    POS = INDEX (VALUE, LABEL(1:N))
		    IF (POS .GT. 0)  RESULT = 1
		ENDIF
	    ENDDO
	ELSE
	    CALL XLGET (UNIT, 'HISTORY', KEYWORD, VALUE, STATUS,
     +			'HIST',TASK,'FORMAT','STRING',' ')
	    IF (STATUS .EQ. 1) THEN
		POS = INDEX (VALUE, LABEL(1:N))
		IF (POS .GT. 0)  RESULT = 1
	    ENDIF
	ENDIF

	CALL XVCLOSE (UNIT, STATUS,' ')


C		CREATE V-BLOCK
	CALL XQINI( VBLOCK, xprdim, xabort)

	CALL XQINTG (VBLOCK, 'RESULT', 1, RESULT, xadd, STATUS)

	CALL XVQOUT( VBLOCK, STATUS)


	RETURN
	END

