      INCLUDE 'VICMAIN_FOR'
C
C     READS NUMBERS IN FROM AN ASCII TEXT FILE INTO AN IBIS 3-D GRAPHICS FILE
C
	SUBROUTINE MAIN44
	IMPLICIT NONE

	CHARACTER*72 INNAME, MSGBUF
	REAL X, Y, Z
	INTEGER COUNT, STATUS, I, WRGR

	CALL XVP ('INPUT', INNAME, COUNT)
        OPEN (UNIT=51, STATUS='OLD', FILE=INNAME)

	STATUS = WRGR(1, 1, 3)
	IF ( STATUS .NE. 1 ) CALL SIGNALGR(1,STATUS,1)

	DO I=1,1000000
	    READ (UNIT=51, FMT=*, IOSTAT=STATUS, END=150)  X,Y,Z
	    IF (STATUS .NE. 0) THEN
		WRITE (MSGBUF, '(A,I6)' )  'READ ERROR IN ROW : ', I
		CALL XVMESSAGE (MSGBUF,' ')
	    ELSE
		CALL PUTGR (1, X, Y, Z)
	    END IF
	END DO
C
  150	CONTINUE
	CALL PUTGR (1, 0.0, 0.0, 0.0)
	CALL CLGR (1)
C
	RETURN
	END
