      INCLUDE 'VICMAIN_FOR'
C VICAR PROGRAM MOMLIST
C
      SUBROUTINE MAIN44

         REAL*8 DN,SIG,VIG,DNSUM,DN2SUM
         REAL*4 BEXPO, EXPOS(30)
         REAL*4 DNS(6400)

         INTEGER NAREA,AREA(4,400)
         INTEGER NI,SL,SS,NL,NS,NL2,NS2,STAT
         INTEGER OUTAREA,AREA_ARRAY(100),AREA_ARRAY_CNT,NEXP

         CHARACTER*132  MSG1
         CHARACTER*255  TABLE_DS
         CHARACTER*1    TAB
         
         LOGICAL ITBL

 
         CALL IFMESSAGE ('*** momlist version 2017-08-09 ***')

         MSG1 = ' '

C-----Open the input Light Transfer File
         CALL XVUNIT(IUNI,'INP',1,STAT,' ')
         CALL XVOPEN(IUNI,STAT,'OPEN_ACT','SA','IO_ACT','SA',' ')
C         CALL XVOPEN(IUNI,STAT,'OPEN_ACT','SA','IO_ACT','SA',
C     &             'U_FORMAT','HALF',' ')

C        Get area size fields...
         CALL XLGET (IUNI,'HISTORY','NUM_AREAS',NAREA,STAT,
     &               'FORMAT','INT','HIST','LTGEN',' ')
         CALL XLGET (IUNI,'HISTORY','AREAS',AREA,STAT,'NELEMENT',
     &               4*NAREA,'FORMAT','INT','HIST','LTGEN',' ')

         CALL XVPARM ('TABLE',TABLE_DS,ICNT,IDEF,1)

         ITBL = ICNT .GT. 0
         TAB = CHAR(9)

         IF (ITBL) THEN 
            OPEN(12,FILE=TABLE_DS,STATUS='UNKNOWN',IOSTAT=JST,ERR=998)
            WRITE(12,10)
     &         'AREA',TAB,'EXPOS',TAB,'MEAN.DN',TAB,'SIGMA'
         END IF

         CALL XVPARM('AREA',AREA_ARRAY,AREA_ARRAY_CNT,IDEF,100) 

         CALL XVSIZE(SL,SS,NL,NS,NL2,NS2)

	 WRITE(MSG1,12) 
     &      'AREA','   ','EXPOS','   ','MEAN.DN','   ','SIGMA'

         CALL XVMESSAGE (MSG1,' ')

         CALL XLGET (IUNI,'HISTORY','NUM_EXPOS',NEXP,STAT,
     &               'FORMAT','INT','HIST','LTGEN',' ')
         CALL XLGET (IUNI,'HISTORY','EXPOSURES',EXPOS,STAT,
     &               'NELEMENT',NEXP,'FORMAT','REAL',
     &               'HIST','LTGEN',' ')

         DO 50 L=1,NL 
            CALL XVREAD (IUNI,DNS,STAT,'LINE',L,'NSAMPS',NS,' ')
            NI = NINT (DNS(1))
            IF (NI .EQ. 0) THEN
               BEXPO = EXPOS(L)
               GOTO 970
            ENDIF
 
            DO 50 K=1,AREA_ARRAY_CNT
               IF (AREA_ARRAY(K) .GT. NAREA) THEN
                  CALL XVMESSAGE ('*** AREA INPUT OUT OF RANGE',' ')
                  WRITE(MSG1,13)
     &               '*** Max input area index =',NAREA
   13             FORMAT (A26,I4)
                  CALL XVMESSAGE (MSG1,' ')
                  CALL ABEND()
               ENDIF 
 	       IB = 3 * NI * (AREA_ARRAY(K)-1) 
               SL = AREA(1,AREA_ARRAY(K))
               SS = AREA(2,AREA_ARRAY(K))
               NL = AREA(3,AREA_ARRAY(K))
               NS = AREA(4,AREA_ARRAY(K))
	       OUTAREA=AREA_ARRAY(K)
               N = NI*NL*NS            !Total number of pixels in area*inputs
               DNSUM = 0.0D0
	       DN2SUM = 0.0D0

               DO I=1,NI
C              Sum of DNs across inputs
                  DNSUM = DNSUM + DBLE(DNS(IB+I+1))
C              Sum of DN*DN across inputs
                  DN2SUM = DN2SUM + DBLE(DNS(IB+I+1+NI))
	       ENDDO

               DN = DNSUM/DBLE(N)              !Average DN for area
               VIG = DN2SUM/DBLE(N) - DN*DN
               IF (VIG .LT. 0.0) THEN
                  CALL XVMESSAGE ('*** INVALID INPUT DATA FILE.',' ')
                  CALL XVMESSAGE
     &               ('*** Please make sure input has been',' ')
                  CALL XVMESSAGE
     &               ('*** correctly generated by MOMGEN.',' ')
                  CALL ABEND()
               ENDIF
               SIG = SQRT(VIG)   ! Calculate Standard Devation

	       WRITE(MSG1,11)
     &            OUTAREA,'   ',EXPOS(L),'   ',DN,'   ',SIG

               CALL XVMESSAGE (MSG1,' ')

               IF (ITBL) 
     &            WRITE(12,9) OUTAREA,TAB,EXPOS(L),TAB,DN,TAB,SIG

   50   CONTINUE

         CALL XVCLOSE(IUNI,IST,' ')
         IF(ITBL) CLOSE(12)

         RETURN
 
    9    FORMAT(1x,I5,A1,F8.2,A1,F8.2,A1,F8.3)
   10    FORMAT(1x,A5,A1,A8,A1,A8,A1,A8)
   11    FORMAT(1x,I5,A3,F8.2,A3,F8.2,A3,F8.3)
   12    FORMAT(1x,A5,A3,A8,A3,A8,A3,A8)
  998    CALL XVMESSAGE ('ERROR OPENING TABLE FILE',' ')
         CALL PRNT(4,1,JST,'IOSTAT =.')
         GO TO 999
  970    CALL PRNT(7,1,BEXPO,'***No data for exposure=.')
         CALL XVMESSAGE
     &     ('***Run MOMGEN on this exposure and try again.',' ')
         GOTO 999
  999    CALL XVMESSAGE ('***MOMLIST task cancelled',' ')
         CALL ABEND
      END
