/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

/*--------------------------------------------------------------------------
 * Apr.     1998  ...S.Le......   Initial release.
 *
 * Apr. 29, 1998  ...T.Huang...   Ported onto Alpha/VMS.
 *                                Cleaned the list of includes.
 *--------------------------------------------------------------------------*/

#include "ms_defines.h"

bool_t
xdr_msProvInfoStruct(xdrs, objp)
	XDR *xdrs;
	msProvInfoStruct *objp;
{
	if (!xdr_vector(xdrs, (char *)objp->institution, 5, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->purpose, 5, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->program_name, 7, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->spk_id, 5, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->request_number, 5, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->year, 5, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->month_day, 5, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->hour_min, 5, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->user_id, 4, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->group_id, 4, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->seg_id, MAX_SEG_ID_LEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_msUserRequestStruct(xdrs, objp)
	XDR *xdrs;
	msUserRequestStruct *objp;
{
	if (!xdr_int(xdrs, &objp->sc_id)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->system)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->scet, 6, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->instrument_name, 64, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->target_name, 64, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->ck_id, 4, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->ck_name, 64, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->ck_source, 4, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->spk_id, 4, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->spk_name, 64, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_msProvInfoStruct(xdrs, &objp->provInfo)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_msCkStruct(xdrs, objp)
	XDR *xdrs;
	msCkStruct *objp;
{
	if (!xdr_int(xdrs, &objp->sc_id)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->instrument)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->system)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->scet, 6, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->av, 3, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_u_char(xdrs, &objp->avFlag)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->c_matrix, 9, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->seg_id, MAX_SEG_ID_LEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->ck_id, 5, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->ck_name, 65, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->ck_source, 5, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_msSpkStruct(xdrs, objp)
	XDR *xdrs;
	msSpkStruct *objp;
{
	if (!xdr_int(xdrs, &objp->sc_id)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->tgt_radius_l_axis)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->tgt_radius_s_axis)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->tgt_polar_radius)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->sc_pos_bd_centered, 3, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->pic_pos_sc_centered, 3, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->rs_vector, 3, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->range_pic_bd_2_sun)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->range_sc_2_central_bd_cntr)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->range_sc_2_picture_bd_cntr)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->tgt_bd_cntr_2_sun_lat)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->tgt_bd_cntr_2_sun_lon)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->tgt_bd_cntr_2_sc_lat)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->tgt_bd_cntr_2_sc_lon)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->me_matrix, 9, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->om_matrix, 9, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->north_angle)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->sub_sc_line)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->sub_sc_samp)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->p5_lat)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->p5_lon)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->p5_incidence_angle)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->p5_emission_angle)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->p5_phase_angle)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->p5_vert_pix_size)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->p5_horiz_pix_size)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->range_sc2p5_intercept_pt)) {
		return (FALSE);
	}
	return (TRUE);
}
