CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C Print input histogram and CDF, as specified
C
      SUBROUTINE PRINT_HISTOGRAM(HIST,IHIST,ICDF,INMAX,
     +	TMEAN,TSIGMA,NPTS)
      IMPLICIT NONE
      INTEGER*4 HIST(-32768:32767),IHIST,ICDF,INMAX,NPTS
      REAL TMEAN,TSIGMA

      INTEGER*4 ICOUNT,IDEF,NSPIKE
      CHARACTER*80 MSG
   40 FORMAT('Histogram of input image: Mean  =',F11.4,
     &          ' Sigma =',F11.4)

      IF (IHIST.EQ.1) THEN		!Print input histogram
         CALL XVMESSAGE(' ',' ')
         CALL XVMESSAGE('INPUT HISTOGRAM',' ')
         CALL XVPARM('SPIKES',nspike,icount,idef,1)
         CALL PHIST(HIST(0),NPTS,0,INMAX,NSPIKE)
         WRITE(MSG,40) TMEAN,TSIGMA
         CALL XVMESSAGE(MSG,' ')
      END IF

      IF (ICDF.EQ.1) THEN		!Print input CDF
         CALL XVMESSAGE(' ',' ')
         CALL XVMESSAGE('CUMULATIVE DISTRIBUTION FUNCTION',' ')  
         CALL CDF(HIST(0),NPTS)
      END IF
      RETURN
      END

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C Print output histogram and CDF (byte only), as specified.
C
      SUBROUTINE PRINT_OHISTOGRAM(HIST,LUT,OHIST,OCDF,NPTS)
      IMPLICIT NONE
      INTEGER*4 HIST(0:255)
      INTEGER*2 LUT(-32768:32767)
      INTEGER*4 OHIST,OCDF,NPTS
      REAL*4 TMEAN,TSIGMA

      COMMON/C3/INMIN,INMAX,DNMIN,DNMAX
      INTEGER*4 INMIN,INMAX,DNMIN,DNMAX

      INTEGER*4 HIST2(0:255)
      INTEGER*4 ICOUNT,IDEF,NSPIKE,IDN,ODN
      CHARACTER*80 MSG
   40 FORMAT('Histogram of output image: Mean=',F11.4,' Sigma=',F11.4)


C     ....Compute output histogram if required (byte case only)
      CALL ZIA(HIST2,256)
      DO IDN=INMIN,INMAX
         ODN = LUT(IDN)
         HIST2(ODN) = HIST2(ODN) + HIST(IDN)
      ENDDO

      IF (OHIST.EQ.1) THEN
         CALL XVMESSAGE(' ',' ')
         CALL XVMESSAGE('OUTPUT HISTOGRAM',' ')
         CALL XVPARM('SPIKES',nspike,icount,idef,1)
         CALL PHIST(HIST2,NPTS,0,DNMAX,NSPIKE)
         CALL STATIB(HIST2,tmean,tsigma,npts)
         WRITE(MSG,40) TMEAN,TSIGMA
         CALL XVMESSAGE(MSG,' ')
      ENDIF
      IF (OCDF.EQ.1) THEN
         CALL XVMESSAGE(' ',' ')
         CALL XVMESSAGE('OUTPUT CUMULATIVE DISTRIBUTION FUNCTION',' ')  
         CALL CDF(HIST2,NPTS)
      ENDIF
      RETURN
      END

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C Print a variable width histogram with spikes option
C  FREQ   - INTEGER ARRAY CONTAINING HISTOGRAM
C  NUM    - INTEGER SUM OF FREQUENCIES OF ALL DN LEVELS
C  NSPIKE - INTEGER NUMBER OF SPIKES TO SKIP IN NORMALIZATION
C  LOWDN  - INTEGER VALUE OF DN LEVEL TO ASSIGN TO HIST(1)
C  HIGHDN - INTEGER VALUE OF THE UPPER DN LEVEL OF THE HISTOGRAM
C
      SUBROUTINE PHIST(FREQ,NUM,LOWDN,HIGHDN,NSPIKE)
      INTEGER FREQ(*),HIGHDN,MAXT,SPIKE
      CHARACTER*132 LISTO
      CHARACTER*23 NUMS
      CHARACTER*103 ASTER/'**************************************************************************************************** *'/
      CHARACTER*103  PLUS/'+         +         +         +         +         +         +         +         +         +        +  '/
      DATA MAXT/2147483647/    ! 2147483647 = z'7FFFFFFF'
  500 FORMAT (I4,I10,F8.3)

      NLEV=HIGHDN-LOWDN+1
      IF(NLEV.LT.1 .OR. NUM.LT.1) THEN
         CALL XVMESSAGE('ERROR IN PHIST ARGUMENT LIST',' ')
         CALL XVMESSAGE('NO HISTOGRAM PRINTED',' ')
         RETURN
      END IF
      SPIKE=NSPIKE+1
      IF(SPIKE.GE.NLEV.OR.SPIKE.LT.1) SPIKE=1
      CALL XVMESSAGE(
     &'GRAY      FREQ  PERCENT   0        10        20        30        40        50        60        70        80        90    100'
     & ,' ')
      CALL XVMESSAGE(' ',' ')
      MAXS=MAXT
      DO J=1,SPIKE
         MAX=0
         DO I=1,NLEV
            IF(FREQ(I).GT.MAX.AND.FREQ(I).LT.MAXS) MAX=FREQ(I)
         ENDDO
         MAXS=MAX
      ENDDO
      IF(MAX.LT.1) MAX=1
      DO I=1,NLEV
         IFREQ=FREQ(I)
         IF(I.GT.1 .AND. IFREQ.EQ.0) THEN
            IF(FREQ(I-1).NE.0) CALL XVMESSAGE(' ',' ')
         ELSE
            PERCEN=(100.0*IFREQ)/NUM
            MTEMP=((100*IFREQ)/MAX)+1
            IF(MTEMP.GT.101) MTEMP=103
            WRITE (NUMS,500) LOWDN+I-1, IFREQ, PERCEN
            LISTO = NUMS//'    '//ASTER(1:MTEMP)//PLUS(MTEMP+1:105)
            CALL XVMESSAGE(LISTO,' ')
         ENDIF
      END DO
      RETURN
      END

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C Compute and print the CDF from the histogram (byte format only).
C
      SUBROUTINE CDF(HIST,NPTS)
      INTEGER*4 HIST(0:255),NPTS

      INTEGER*4 CDFUN(0:255),I,IMAX

      CDFUN(0) = HIST(0)
      IMAX = 0
      DO I=1,255
         CDFUN(I) = CDFUN(I-1) + HIST(I)
         IF (HIST(I).GT.0) IMAX=I
      END DO
      CALL PHIST(CDFUN,NPTS,0,IMAX,0)
      RETURN
      END
