#!/bin/sh

#SYBASE=/usr/local/sybase
#export SYBASE

SYBASE_SYSAM=SYSAM-1_0
export SYBASE_SYSAM
SYBASE_ASE=ASE-12_5
export SYBASE_ASE
SYBASE_OCS=OCS-12_5
export SYBASE_OCS
SYBASE_JRE=${SYBASE}/shared-1_0/jre1.2.2
export SYBASE_JRE
SYBASE_FTS=EFTS-12_5
export SYBASE_FTS

PATH=$SYBASE/$SYBASE_ASE/bin:$SYBASE/$SYBASE_OCS/bin:$SYBASE/CFG-1_0:$PATH
export PATH
LM_LICENSE_FILE=$SYBASE/$SYBASE_SYSAM/licenses/license.dat:$LM_LICENSE_FILE
export LM_LICENSE_FILE
LD_LIBRARY_PATH=$SYBASE/$SYBASE_ASE/lib:/usr/local/openwin/lib:$SYBASE/$SYBASE_FTS/lib:$SYBASE/$SYBASE_OCS/lib:/usr/local/openwin/lib:/usr/lib:$SYBASE/SQLRemote/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH
