	INCLUDE 'VICMAIN_FOR'
	SUBROUTINE MAIN44
	CHARACTER*3 ORG
C							   open dataset (update)
	CALL XVUNIT(IUNIT,'INP',1,ISTAT,' ')
	CALL XVOPEN(IUNIT,ISTAT,'OP','UPDATE','OPEN_ACT','SA',
     +		    'IO_ACT','SA',' ')
C								store old values
	CALL XVGET(IUNIT,ISTAT,'NL',NL,'NS',NS,'NB',NB,'ORG',ORG,' ')
	CALL XLADD(IUNIT,'HISTORY','3D_NL',NL,ISTAT,'FORMAT','INT',' ')
	CALL XLADD(IUNIT,'HISTORY','3D_NS',NS,ISTAT,'FORMAT','INT',' ')
	CALL XLADD(IUNIT,'HISTORY','3D_NB',NB,ISTAT,'FORMAT','INT',' ')
	CALL XLADD(IUNIT,'HISTORY','3D_ORG',ORG,ISTAT,'FORMAT','STRING',
     +		   ' ')
C							       delete old values
	CALL XLDEL(IUNIT,'SYSTEM','NL',ISTAT,'ERR_ACT','SA',' ')
	CALL XLDEL(IUNIT,'SYSTEM','NS',ISTAT,'ERR_ACT','SA',' ')
	CALL XLDEL(IUNIT,'SYSTEM','NB',ISTAT,'ERR_ACT','SA',' ')
	CALL XLDEL(IUNIT,'SYSTEM','ORG',ISTAT,'ERR_ACT','SA',' ')
C							    calculate new values
	IF (ORG.EQ.'BIP') THEN
	    NL = NL*NS
	    NS = NB
	ELSE
	    NL = NL*NB
	END IF
	ORG = 'BSQ'
	NB = 1
C								  add new values
	CALL XLADD(IUNIT,'SYSTEM','NL',NL,ISTAT,'FORMAT','INT',' ')
	CALL XLADD(IUNIT,'SYSTEM','NS',NS,ISTAT,'FORMAT','INT',' ')
	CALL XLADD(IUNIT,'SYSTEM','NB',NB,ISTAT,'FORMAT','INT',' ')
	CALL XLADD(IUNIT,'SYSTEM','ORG',ORG,ISTAT,'FORMAT','STRING',' ')
C
	RETURN
	END
