      INCLUDE 'VICMAIN_FOR'
      SUBROUTINE MAIN44
C
C  11 DEC 85   ...REW...    CREATION DATE
C  29 APR 91   ...REA...    CONVERTED TO UNIX/VICAR
C
C
C		** Declare variables **
C
	INTEGER BUFLEN, NSTRIPS, ISS(100)
	INTEGER SL, SS, NS, NLINES, NSSTRIP, ISTRIP, ILINE
	INTEGER OUT, NL, ISTAT, INLINE, IGAP, INP(10)
	LOGICAL*1 BUF(10000)
	LOGICAL FLAG
C
C		** Process parameters **
C
	FLAG = .TRUE.
	CALL XVPARM('STRIPLEN',NLINES,NNL,ISTAT,0)
	CALL XVPARM('GAPWIDTH',IGAP,NGP,ISTAT,0)
C
C		** Open input data set for first time **
C
	CALL XVUNIT(INP(1),'INP',1,ISTAT,' ')
	CALL XVOPEN(INP(1),STAT,'OPEN_ACT','SA','IO_ACT','SA',' ')
C
C		** Set up necessary parameters **
C
	CALL XVSIZE(SL,SS,NL,NS,NLIN,NSIN)
	NSTRIPS = (NL + NLINES-1)/NLINES
	DO I = 2,NSTRIPS
	    CALL XVUNIT(INP(I),'INP',I,ISTAT,' ')
	    CALL XVOPEN(INP(I),STAT,'OPEN_ACT','SA','IO_ACT','SA',' ')
	ENDDO
C
	NSSTRIP = NS + IGAP
	BUFLEN  = NSTRIPS*(NSSTRIP)-IGAP
	IF (BUFLEN.GT.10000) THEN
	    CALL XVMESSAGE(
     +	       ' Output image must be no more than 10,000 samples wide',
     +	       ' ')
	    CALL ABEND
	ENDIF
C
C		** Open output data set **
C
	CALL XVUNIT(OUT,'OUT',1,STAT,' ')
	CALL XVOPEN(OUT,STAT,'OPEN_ACT','SA','IO_ACT','SA','U_NL',
     &		NLINES,'U_NS',BUFLEN,'U_ORG','BSQ','OP','WRITE',
     &		'O_FORMAT','BYTE',' ')
C
C		** Set up pointers for XVREAD **
C
	DO ISTRIP = 1,NSTRIPS
	    ISS(ISTRIP) = (ISTRIP-1)*(NS+IGAP)+1
	ENDDO
C
	DO ILINE = 1, NLINES
	    INLINE = ILINE+SL-1
	    DO ISTRIP = 1, NSTRIPS
		IF(INLINE.LE.NLIN) THEN
		    CALL XVREAD(INP(ISTRIP),BUF(ISS(ISTRIP)),ISTAT,
     &		    'LINE',INLINE,'SAMP',SS,'NSAMPS',NS,' ')
		    INLINE = INLINE + NLINES
		ELSE
		    IF(FLAG) THEN
			CALL ITLA(0,BUF(ISS(ISTRIP)),NSSTRIP)
			FLAG = .FALSE.
		    ENDIF
		ENDIF
	    ENDDO
	    CALL XVWRIT(OUT,BUF,ISTAT,'NSAMPS',BUFLEN,' ')
	ENDDO
C
	DO ISTRIP = 1, NSTRIPS
	    CALL XVCLOSE(INP(ISTRIP),STAT,' ')
	ENDDO
	CALL XVCLOSE(OUT,STAT,' ')
	RETURN
	END
