	SUBROUTINE HSTGNB(NSAMP,PIXLIN,HIST)
C	THIS SUBROUTINE GENERATES A HISTOGRAM ON BYTE DATA.
C	EACH CALL TO THE SUBROUTINE PROCESSES ONE PICTURE LINE.
C	IT IS ASSUMED THE DATA IS STILL IN PACKED FORMAT
C	ARGUMENT LIST
C	NSAMP     NUMBER OF SAMPLES IN A PICTURE LINE
C	PIXLIN    ARRAY CONTAINING ONE PICTURE LINE
C	HIST      ARRAY CONTAINING RUNNING ACCUMULATION FOR HISTOGRAM 256 WORDS
C	NRANGE    RUNNING TOTAL OF VALUES OUTSIDE THE RANGE OF 0-255
C	6/3/83 -JAM- INITIAL CODING
C	8/29/84 SP - REPLACED CALL TO MVE WITH IZEXT FUNCTION
C       10/31/94 AS - CRI MSTP S/W CONVERSION (VICAR PORTING)
C
        INCLUDE 'fortport'
	BYTE PIXLIN(*)
	INTEGER*4 HIST(256)
	DO I=1,NSAMP
	    INDEX= 1 + BYTE2INT( PIXLIN(I) )
	    HIST(INDEX)=HIST(INDEX)+1
	ENDDO	       
	RETURN
	END

