      INCLUDE 'VICMAIN_FOR'
      SUBROUTINE MAIN44
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     THIS IS A TEST FOR MODULE INTRPA   C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C                                        C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C  RUN THROUGH ALL OF THE DATA TYPES     C
C  I.E. INTERPOLATE BYTE, HALF AND       C
C  FULL WORD DATA                        C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      BYTE       B(10)             !BYTE VARIABLES
      INTEGER*2  H(10)             !HALFWORD VARIABLE
      INTEGER*4  F(10)             !FULLWORD VARIABLE
      CHARACTER  CARD*80           !PRINT BUFFER

      CALL XVMESSAGE(' ',' ')
      CALL XVMESSAGE('**BEGIN TEST OF MODULE INTRPA**',' ')


      CALL XVMESSAGE(' ',' ')
      CALL XVMESSAGE('**BYTE DATA**',' ')
      CALL INTRPA(1, 10, B, 1, 10)
      WRITE(CARD, 100) B
      CALL XVMESSAGE(CARD,' ')

      CALL XVMESSAGE(' ',' ')
      CALL XVMESSAGE('**HALFWORD DATA**',' ')
      CALL INTRPA(2, 10, H, 1, 10)
      WRITE(CARD, 100) H
      CALL XVMESSAGE(CARD,' ')

      CALL XVMESSAGE(' ',' ')
      CALL XVMESSAGE('**FULLWORD DATA**',' ')
      CALL INTRPA(4, 10, F, 1, 10)
      WRITE(CARD, 100) F
      CALL XVMESSAGE(CARD,' ')

      CALL XVMESSAGE('**END TEST OF MODULE INTRPA**',' ')
      CALL XVMESSAGE(' ',' ')

      CALL XVMESSAGE(
     + 'Repeat test cases in C to test C interface: zintrpa',' ')
      call tzintrpa
      RETURN
 100  FORMAT(1X, 10Z5.2)

      END
