C TO TEST SUBROUTINE LOGO
C TO TEST JPL LOGO WITH IDN=255
      INCLUDE 'VICMAIN_FOR'
      SUBROUTINE MAIN44
      BYTE BUF(64)
      LOGICAL  XVPTST
      INTEGER ICODE

      CALL XVUNIT(OUNIT,'OUT',1,STAT,' ')
      CALL XVOPEN(OUNIT,STAT,'OP','WRITE','O_FORMAT','BYTE',
     &            'U_FORMAT','BYTE','U_NL',64,'U_NS',64,' ')

      IF(XVPTST('JPL'))  ICODE=1
      IF(XVPTST('MICK')) ICODE=2
      IF(XVPTST('GODD')) ICODE=3
      IF(XVPTST('NASA')) ICODE=4

      DO I=1,64
         CALL ITLA(0,BUF,64)
         IF ( MOD(I,2) .EQ. 1) THEN
           CALL LOGO(255,I,ICODE,0,BUF)    ! ALTERNATE BETWEEN TRYING FROM
         ELSE 
           CALL TZLOGO(255,I,ICODE,0,BUF)  ! FORTRAN AND FROM C.
         END IF
         CALL XVWRIT(OUNIT,BUF,STAT,'NSAMPS',64,' ')
      ENDDO

      CALL XVCLOSE(OUNIT,STAT,' ')

      RETURN
      END

