C     THIS SUBROUTINE WILL BE USED TO SORT THE LINES AND SAMPLES IN ASCENDING
C     ORDER USING LINE VALUES.

      SUBROUTINE SORTX(BUF,N)

      INTEGER*2 BUF(2,4000)
C
      DO 100 I=1,N
      J=BUF(1,I)
      BUF(1,I)=BUF(2,I)
      BUF(2,I)=J
100   CONTINUE

      CALL SORTIN(BUF,N)

      DO 200 I=1,N
      J=BUF(1,I)
      BUF(1,I)=BUF(2,I)
      BUF(2,I)=J
200   CONTINUE

      RETURN
      END
